
<script language='Javascript'>

    function UpdateLandedCost()
    {
        if (!isNaN(parseFloat($('#UnitPriceRM').val()))){
            UnitPriceRM = parseFloat($('#UnitPriceRM').val());
            $('#UnitPriceRM').val(parseFloat($('#UnitPriceRM').val()).toFixed(2));
        }

        if (!isNaN(parseFloat($('#UnitDeliveryCost').val()))){
            UnitDeliveryCost = parseFloat($('#UnitDeliveryCost').val());
            $('#UnitDeliveryCost').val(parseFloat($('#UnitDeliveryCost').val()).toFixed(2));
        }


        if (!isNaN(parseFloat($('#UnitTaxCost').val()))){
            UnitTaxCost = parseFloat($('#UnitTaxCost').val());
            $('#UnitTaxCost').val(parseFloat($('#UnitTaxCost').val()).toFixed(2));
        }
        var LandedCost = parseFloat(UnitPriceRM + UnitDeliveryCost + UnitTaxCost).toFixed(2);
        $('#UnitLandedCost').val(LandedCost);

        var retailPrice = parseFloat((($('#MarkupPercent').val() / 100) * LandedCost)) + parseFloat(LandedCost);
        $('#UnitRetail').val(parseFloat(retailPrice).toFixed(2));

//	var MarkupPercent = 0.00;
//	if (parseFloat($('#RetailPrice').val()) >= parseFloat($('#UnitLandedCost').val()))
//		MarkupPercent =  ((parseFloat($('#RetailPrice').val()) - parseFloat($('#UnitLandedCost').val())) / parseFloat($('#UnitLandedCost').val())) * 100;
//	else
//		MarkupPercent =  "-" + (((parseFloat($('#UnitLandedCost').val()) - parseFloat($('#RetailPrice').val())) / parseFloat($('#RetailPrice').val()))) * 100;
//
//	$('#MarkupPercent').val(parseFloat(MarkupPercent).toFixed(2));
    }

    function OnDeleteStatus(item_id){
        $.prompt(
            "<?=$this->translate->_('Are you sure you want to remove this entry?')?>",{
                buttons: { Ok: true, Cancel: false },
                submit:function(e,v,m,f){
                    if(v){
                        document.location='/inventory/rental/detail/id/<?=$this->RentalAssetID?>/remove_status/'+item_id;
                    }
                }

            });
    }




    $(document).ready(function() {

        $( "#StatusDate" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
        $( "#EstimatedReturnDate" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
        $( "#EstimatedReturnDateExtension" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
        $( "#ActualReturnDate" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});

        if ($('#StatusItem').val() == "sold" || $('#StatusItem').val() == "reserved")
        {
            $('#divSalesOrder').show();
        }

        $('#UnitPriceRM').change(function () {
            UpdateLandedCost();
        });

        $('#UnitDeliveryCost').change(function () {
            UpdateLandedCost();
        });

        $('#UnitTaxCost').change(function () {
            UpdateLandedCost();
        });

        $('#MarkupPercent').change(function () {
            UpdateLandedCost();
        });


        $("#StatusDate").change(function(){
            if ($('#RentalStatus').val() == "returned"){
                $('#ActualReturnDate').val($("#StatusDate").val());
            }
        })


        $('#StatusItem').change(function () {
            if ($('#StatusItem').val() == "sold")
            {
                $('#divSalesOrder').show();
            }else
                $('#divSalesOrder').hide();
        });


        $('#RentalStatus').change(function () {
            if ($('#RentalStatus').val() == "out"){
                $('.clsOutRental').show();
                $('.clsRentalExtension').hide();

            }
            else if ($('#RentalStatus').val() == "returned"){
                $('.clsOutRental').hide();
                $('.clsRentalExtension').hide();

            }
            else if ($('#RentalStatus').val() == "extension"){
                $('.clsOutRental').hide();
                $('.clsRentalExtension').show();

            }else{
                $('.clsOutRental').hide();
                $('.clsRentalExtension').hide();
            }

        });


        $('#add_status').click(function () {
            var error = false;
            if ($('#StatusDate').val()=='') {

                $('#StatusDate').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter the date')?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'inner-left',alignY: 'top',offsetX: 5, timeOnScreen: 3000});
                $('#StatusDate').poshytip('show');
                $('#StatusDate').css("border", "1px solid red");

                error = true;
            }

            if ($('#RentalStatus').val()=='') {

                $('#RentalStatus').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please select the status')?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'inner-left',alignY: 'bottom',offsetX: 5, timeOnScreen: 3000});
                $('#RentalStatus').poshytip('show');
                $('#RentalStatus').css("border", "1px solid red");

                error = true;
            }

            if ($('#UserIDResp').val()=='') {

                $('#UserIDResp').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please select the person in charge')?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'inner-left',alignY: 'top',offsetX: 5, timeOnScreen: 3000});
                $('#UserIDResp').poshytip('show');
                $('#UserIDResp').css("border", "1px solid red");

                error = true;
            }

            if ($('#RentalStatus').val()=='out' && $('#ClientName').val()=='') {

                $('#ClientName').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please select the customer')?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'inner-left',alignY: 'top',offsetX: 5, timeOnScreen: 3000});
                $('#ClientName').poshytip('show');
                $('#ClientName').css("border", "1px solid red");

                error = true;
            }

            if ($('#RentalStatus').val()=='out' && $('#EstimatedReturnDate').val()=='') {

                $('#EstimatedReturnDate').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter estimated return date')?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'inner-left',alignY: 'bottom',offsetX: 5, timeOnScreen: 3000});
                $('#EstimatedReturnDate').poshytip('show');
                $('#EstimatedReturnDate').css("border", "1px solid red");

                error = true;
            }

            if ($('#RentalStatus').val()=='returned' && $('#ActualReturnDate').val()=='') {

                $('#ActualReturnDate').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter return date')?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'inner-left',alignY: 'bottom',offsetX: 5, timeOnScreen: 3000});
                $('#ActualReturnDate').poshytip('show');
                $('#ActualReturnDate').css("border", "1px solid red");

                error = true;
            }

//		if ($('#Notes').val()=='') {
//
//			$('#Notes').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter the notes for this entry')?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'inner-left',alignY: 'bottom',offsetX: 5, timeOnScreen: 3000});
//			$('#Notes').poshytip('show');
//			$('#Notes').css("border", "1px solid red");
//
//			error = true;
//		}

            if (error)
                return false;
            else
                return true;

        });

        $(document).on("click", "#idDeleteDoc", function(event){
            var RentalStatusDocumentsID = $(this).attr("RentalStatusDocumentsID");
            $objDel = $(this);
            $.prompt("<?=$this->translate->_('Delete the document?')?>",{
                buttons: { Ok: true, Cancel: false },
                submit:function(e,v,m,f){
                    if(v){
                        $.post("/inventory/rental/doc-delete",{RentalStatusDocumentsID:RentalStatusDocumentsID},function(result){
                            $objDel.parent().remove();
                        });
                    }
                }
            });


        });


        $(document).on("click", ".clsUploadDoc", function(event){
            var JobID = $(this).attr("JobID");
            var RentalAssetStatusID = $(this).attr("RentalAssetStatusID");
            //var objUpload = $(this).parent().parent();
            var objUpload = $(this).parent().parent();

            $('#idDialog').dialog({title: "Supporting Documents", modal: true, minWidth: 500,maxHeight: 600,
                position: {my: "top+50%", at: "top", of: window},
                buttons: {
                    'Close': function() {
                        $('#idDialog').dialog('close');
                        objUpload.html("<img src='/images/icons/IconIndicator.gif'>");
                        $.post("/inventory/rental/doc-get-list",{RentalAssetStatusID:RentalAssetStatusID},function(result){
                            console.log(result);
                            objUpload.html(result);
                            objUpload.addClass("md-input-success");
                        });

                        //	location.reload();
                    }
                },
                open: function( event, ui ) {
                    $(this).html("<img src='/images/icons/IconIndicator.gif'>");
                    $(this).load("/inventory/rental/doc-upload-form",{RentalAssetStatusID:RentalAssetStatusID});


                },
                destroy: function( event, ui ) {
                }
            });
        });



        $(document).on("submit", ".clsFormDoc", function(event){
            event.preventDefault();
            var objEntry = $(this);
            var formData = new FormData(this);


            var error = false;

            if ($(this).find(".clsName").val() == "")
            {

                $(this).find(".clsName").poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"> Please enter document name.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
                $(this).find(".clsName").poshytip('show');
                $(this).find(".clsName").css("border", "1px solid red");
                error = true;
            }

            if ($(this).find(".clsDocUpload").val() == "")
            {
                $(this).find(".clsDocUpload").poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"> Please select a document to upload.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'center',alignY: 'bottom',offsetX: 5, timeOnScreen: 3000});
                $(this).find(".clsDocUpload").poshytip('show');
                $(this).find(".clsDocUpload").css("border", "1px solid red");
                error = true;
            }

            if (!error){
                objEntry.find("#UploadStatus").html("<img src='/images/icons/IconIndicator.gif'>");
                var RentalAssetStatusID = objEntry.find("#RentalAssetStatusID").val();
                var url=objEntry.attr("action");
                $.ajax({
                    url: url,
                    type: objEntry.attr("method"),
                    dataType: "html",
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (data, status)
                    {
                        if (data == "ERRORSIZE")
                        {
                            $.prompt("Please upload file that is less than 5MB in size.", {buttons: { Ok: true}});
                        }else if (data == "ERROR_IMAGETYPE")
                        {
                            $.prompt("Please upload files with jpg, png, pdf, doc, docx, xls or xlsx file types.", {buttons: { Ok: true}});
                        }else
                        {
                            $("#idUploadedDoc").prepend(data);
                        }
                        objEntry.find("#UploadStatus").html("");
                        objEntry.find(".clsDocUpload").val("");
                        objEntry.find(".clsName").val("");
                        objEntry.find(".clsDescription").val("");

                    }

                })
            }
        })


    });

</script>


<div id='idDialog'></div>
<B class='PageHeader'><?=$this->translate->_('Rental Asset Details')?></B><BR>

<?
$disableEdit = true;
if ($this->userInfo->ACLRole != "User" && $this->userInfo->ACLRole != "Sales" && $this->userInfo->ACLRole != "Account" ) {
    $disableEdit = false;
}
?>

<form  action='/inventory/rental/detail/id/<?=$this->RentalAssetID?>' method=POST>
    <table border=0 cellspacing=2 cellpadding=2 width=700px>

        <TR><TD colspan=2 ><B><?=$this->ItemFullName?></B></TD></TR>
        <? if ($this->ItemImagePath) { ?>
            <TR><TD colspan=2 ><B><img style="max-height:100px;max-width:150px;" src='<?=$this->ItemImagePath?>'></B></TD></TR>
        <? } ?>
        <TR><TD class='form_label' width=150px><?=$this->translate->_('PO Number')?></TD>
            <TD  style='text-align: right;' width=150px  class='form_field' valign=bottom><?=$this->OrderNumber?></TD></TR>
        <TR><TD class='form_label' width=150px><?=$this->translate->_('Date of Purchase')?></TD><TD style='text-align: right;' class='form_field'><?=$this->PurchaseDate?></TD></TR>
        <TR><TD class='form_label' width=150px><?=$this->translate->_('Item')?></TD><TD style='text-align: right;' class='form_field'>
                <select disabled name='ItemID' style="width:450px;" id='ItemID' title="Items."><option value=''>-<?=$this->optionItems?></select></TD></TR>
        <TR><TD class='form_label' width=150px><?=$this->translate->_('Serial Number')?></TD><TD  style='text-align: right;' class='form_field'>
                <input  style='text-align: right;' type=text name='SeriesNumber' ID='SeriesNumber' value='<?=$this->SeriesNumber?>' <?=$disableEdit ? "disabled" : ""?>>
            </TD></TR>
        <TR><TD class='form_label' width=150px><?=$this->translate->_('Branch')?></TD><TD class='form_field' valign=bottom  style='text-align: right;'>
                <select disabled name='BranchID' id='BranchID' title="">
                    <option value=''>-</option><?=$this->optionBranches?>
                </select>
            </TD></TR>

        <TR><TD class='form_label' width=150px><?=$this->translate->_('Stock Status')?></TD><TD  style='text-align: right;' class='form_field'>

                <SELECT <?=!$this->add_series ? "disabled" : ""?> name='StatusItem' id='StatusItem'><option value=''>-</option><?=$this->optionStatusItem?></SELECT>
                <div id='divSalesOrder' style='display:none;padding-top:4px; text-align:right;'> <?=$this->translate->_('Sales Order Number')?>: <input <?=$disableEdit ? "disabled" : ""?> type=text id='SalesOrderNumber' name='SalesOrderNumber' value='<?=$this->SalesOrderNumber?>'><?=$this->SOLink?></div>
            </TD></TR>

        <TR><TD class='form_label' width=150px><?=$this->translate->_('Available Rental Stock')?></TD><TD  style='text-align: right;' class='form_field'>
            <?=$this->NumStockAvailable?>
        </TD></TR>
        <TR><TD class='form_label' width=150px><?=$this->translate->_('Total Rental Stock')?></TD><TD  style='text-align: right;' class='form_field'>
            <?=$this->NumStockTotal?>
        </TD></TR>
        <TR><TD class='form_label' width=150px><?=$this->translate->_('Initial Remaining Lifespan (Months)')?></TD><TD  style='text-align: right;' class='form_field'>
                As of: <u><?=$this->DateAsAsset?></u>
                <input  style='text-align: right;' size=3  type=text name='MonthRemaining' ID='MonthRemaining' value='<?=$this->MonthRemaining?>' <?=$disableEdit ? "disabled" : ""?>>
        </TD></TR>
        <TR><TD class='form_label' width=150px><?=$this->translate->_('Total Lifespan (Months)')?></TD><TD  style='text-align: right;' class='form_field'>
                <input  style='text-align: right;' size=3 type=text name='MonthDepreciation' ID='MonthDepreciation' value='<?=$this->MonthDepreciation?>' <?=$disableEdit ? "disabled" : ""?>>
            </TD></TR>
        <TR><TD colspan=2 class='form_field'>&nbsp;</TD></TR>
        <TR><TD colspan=2 class='form_field'>
                <? if ($this->userInfo->ACLRole != "User" && $this->userInfo->ACLRole != "Sales" && $this->userInfo->ACLRole != "Account" ) { ?>
                        <input type=submit id='update_item' name='update_item' value='<?=$this->translate->_('Update Details')?>'>
                <? } ?>
                <input type="hidden" name="ItemSeriesID" value="<?=$this->ItemSeriesID?>">
                <input type=button id='back' name='back' value='<?=$this->translate->_('Back')?>' onclick="document.location='/inventory/rental'">

            </TD></TR>
    </table>
</form>

<?
if (!$this->add_series) {
?>

    <form  action='/inventory/rental/detail/id/<?=$this->RentalAssetID?>' method=POST>
        <table border="0" align="class='report_table'" id="report_table" cellspacing="0" cellpadding="3">
            <tbody><tr>
                <td class="report_header" style="text-align:center"><?=$this->translate->_('Reference Number')?></td>
                <td class="report_header" style="text-align:center"><?=$this->translate->_('Date')?>*</td>
                <td class="report_header" style="text-align:center"><?=$this->translate->_('Status')?>*</td>
                <td class="report_header" style="text-align:left; min-width: 250px"><?=$this->translate->_('Status Detail')?>*</td>
                <td class="report_header" style="text-align:center"><?=$this->translate->_('Person In Charge')?>*</td>
                <td class="report_header" style="text-align:center"><?=$this->translate->_('Notes')?>*</td>
                <td class="report_header" style="text-align:center"><?=$this->translate->_('Entry By')?></td>
                <td class="report_header" style="text-align:center"><?=$this->translate->_('Entry date')?></td>
                <td class="report_header" style="text-align:center">&nbsp;</td>
            </tr>
            <? if ($this->userInfo->ACLRole != "User" && $this->userInfo->ACLRole != "Sales" && $this->userInfo->ACLRole != "Account" ) { ?>

                <tr>
                    <td class="report_even" style="text-align:center"><input type=text size=8 name='ReferenceNo' id='ReferenceNo'></td>
                    <td width=180px class="report_even" style="text-align:center">
                        <div id="divStatusDate">
                            <input type=text size=10 name='StatusDate' id='StatusDate'>
                        </div>
                    </td>
                    <td class="report_even" style="text-align:center">
                        <SELECT name='RentalStatus' id='RentalStatus'><option value=''>-</option><?=$this->optionRentalStatus?></SELECT>
                    </td>

                    <td class="report_even" style="text-align:center;">
                        <div class="clsOutRental" style="display: none">
                            Customer:<BR>
                            <select <?=$this->userInfo->ACLRole == "User" ? "disabled" : ""?> name='ClientName' id='ClientName' title=""><option value=''>-</option><?=$this->optionCustomers?></select><BR>
                            Estimated Return Date:<BR>
                            <input type=text size=10 name='EstimatedReturnDate' id='EstimatedReturnDate'>

                        </div>
                        <div class="clsRentalExtension" style="display: none">
                            Estimated Return Date:<BR>
                            <input type=text size=10 name='EstimatedReturnDateExtension' id='EstimatedReturnDateExtension'>

                        </div>

                    </td>

                    <td class="report_even" style="text-align:center"><SELECT name='UserIDResp' id='UserIDResp' ><option value=''>-</option><?=$this->optionPersonInCharge?></SELECT></td>
                    <td class="report_even" style="text-align:center"><textarea name='Notes' id='Notes'></textarea></td>
                    <td class="report_even" style="text-align:center">&nbsp;</td>
                    <td class="report_even" style="text-align:center">&nbsp;</td>
                    <td class="report_even" style="text-align:center"><input type=submit name='add_status' id='add_status' value='<?=$this->translate->_('Add New Status')?>'></td>
                </tr>
            <? } ?>

            <?=$this->status?>

            </tbody></table>
    </form>

<? } ?>
