<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">  
<head>
 <?php $this->headTitle("Sample Modular Zend_Application Example"); ?>
 <?php $this->headLink()->appendStylesheet('/styles/style_ie.css', 'screen, projection', 'IE'); ?>
 <?php $this->headLink()->appendStylesheet('/styles/style.css', 'screen, projection'); ?>
 <?= $this->headLink(); ?>
 
 </head>
 <body>
THIS IS ADMIN LAYOUT as as a asdasd
 </body>
 </html>