
<script language='Javascript'>
function SavePO()
{
	var error = false;
	
	if ($('#OrderNumber').val()=='') { 
		
		$('#OrderNumber').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please enter the PO Number")?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
		$('#OrderNumber').poshytip('show');
		$('#OrderNumber').css("border", "1px solid red");
		
		error = true;
	}
	
		
	if ($('#VendorID').val()=='' || $('#VendorID').val()=='add-new' ) { 
		
		$('#VendorID').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please select the vendor")?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
		$('#VendorID').poshytip('show');
		$('#VendorID').css("border", "1px solid red");
		error = true;
	}
	if ($('#BranchID').val()=='' || $('#BranchID').val()=='add-new' ) { 
		
		$('#BranchID').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please select the branch")?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
		$('#BranchID').poshytip('show');
		$('#BranchID').css("border", "1px solid red");
		
		error = true;
	}	
	$( "[id='ItemID']" ).each(function( index, element  ) {
	
		//console.log("ItemID" + element.value);
	
		if ((element.value == "" || element.value == "0")  && !error )
		{
			$.prompt("<?=$this->translate->_("Please select the item before clicking Save")?>.",{ title: "<?=$this->translate->_("Invalid Entry")?>", buttons: { Ok: true }});
			$(element).css("border", "1px solid red");
			error = true;	
		}
	});	
		
	//return false;
	var totalPrice = 0;
	$( "[id='Quantity']" ).each(function( index, element  ) {
		if ((isNaN(element.value) || element.value == 0) && !error ){
			$.prompt("<?=$this->translate->_("Please enter all the valid quantity for all the items")?>.",{ title: "<?=$this->translate->_("Invalid Entry")?>", buttons: { Ok: true }});
			$(element).css("border", "1px solid red");
			
			
			error = true;		
		}
	});	
	

		
		
	if (error)
		return false; 
	else
		return true;
}

function ResetItemNumbers()
{
	$( "[id='itemcounter']" ).each(function( index, element  ) {
		element.innerHTML = (index + 1);
	});
}

function CalculateRMConvert()
{
	var ProductCost = 0;
	var Multiplier = 0;
	
	if (!isNaN(parseFloat($('#ProductCost').val()))){
		ProductCost = parseFloat($('#ProductCost').val());
	}
	if (!isNaN(parseFloat($('#Multiplier').val()))){
		Multiplier = parseFloat($('#Multiplier').val());
	}
	
	$('#ProductCostRM').val(parseFloat(parseFloat(ProductCost) * parseFloat(Multiplier)).toFixed(2));
	CalculateFinalCosting();
}

function CalculateFinalCosting()
{
	var ProductCostRM = 0;
	var PODeliveryCost = 0;
	//var MiscCost = 0;
	var POTaxCost = 0;
	var PODiscount = 0;


	
	if (!isNaN(parseFloat($('#ProductCostRM').val()))){
		ProductCostRM = parseFloat($('#ProductCostRM').val());
		$('#ProductCostRM').val(parseFloat($('#ProductCostRM').val()).toFixed(2));
	}
	
	if (!isNaN(parseFloat($('#PODeliveryCost').val()))){
		PODeliveryCost = parseFloat($('#PODeliveryCost').val());
		$('#PODeliveryCost').val(parseFloat($('#PODeliveryCost').val()).toFixed(2));
	}
		

	if (!isNaN(parseFloat($('#POTaxCost').val()))){
		POTaxCost = parseFloat($('#POTaxCost').val());
		$('#POTaxCost').val(parseFloat($('#POTaxCost').val()).toFixed(2));
	}
	
//	if (!isNaN(parseFloat($('#PODiscount').val()))){
//		PODiscount = parseFloat($('#PODiscount').val());
//		$('#PODiscount').val(parseFloat($('#PODiscount').val()).toFixed(2));
//	}
	
	$('#TotalCost').val(parseFloat(PODeliveryCost + ProductCostRM + POTaxCost).toFixed(2));
}

function CalculateDifference()
{



		var totalPrice = 0;
		$( "[id='TotalItemPrice']" ).each(function( index, element  ) {
			if (isNaN(parseFloat(element.value)))
				totalPrice += 0;
			else{
				totalPrice += parseFloat(element.value);
				element.value = parseFloat(element.value).toFixed(2);
			}
		});	
		
		var valCostFromItems = parseFloat(totalPrice).toFixed(2);
		var valCostFromItemsDiff = parseFloat((parseFloat($( "#ProductCostRM" ).val()) - parseFloat(totalPrice))).toFixed(2);
		if (isNaN(valCostFromItems))
			$( "#ProductCostFromItems" ).val("");
		else
			$( "#ProductCostFromItems" ).val("RM " + valCostFromItems);
		
		if (isNaN(valCostFromItemsDiff))
			$( "#ProductCostFromItemsDiff" ).val("");
		else
			$( "#ProductCostFromItemsDiff" ).val("RM " + valCostFromItemsDiff);
		
		
		if ((valCostFromItems) != $( "#ProductCostRM" ).val())
		{
			$( "#ProductCostFromItemsDiff" ).css("border", "solid 1px #EF4545");
			$( "#ProductCostFromItems" ).css("border", "solid 1px #EF4545");
		}else{
			$( "#ProductCostFromItemsDiff" ).css("border", "solid 1px #45EF45");
			$( "#ProductCostFromItems" ).css("border", "solid 1px #45EF45");
		}
		
		CalculateAverageAdditional();
}
function getNumber(theNumber)
{
    if(theNumber > 0){
        return "+" + theNumber;
    }else{
        return theNumber.toString();
    }
}
function CalculateAverageAdditional()
{

	if (!isNaN(parseFloat($('#PODeliveryCost').val()))){
		PODeliveryCost = parseFloat($('#PODeliveryCost').val());
	}

	var totalAdditional = PODeliveryCost;

	var totalSize = $( "[id='DeliveryCost']" ).size();
	var averageAdditionalDisplay = parseFloat(totalAdditional / totalSize).toFixed(2);
	
	//alert(averageAdditionalDisplay);
	var averageAdditional = parseFloat(totalAdditional / totalSize).toFixed(3);
	
	var totalQuantity = 0;
	var totalUnitPrice = 0;
	var totalTaxCost = 0;
	var totalDeliveryCost = 0;
	var totalTotalItemPrice = 0;
	var totalTotalPriceXDiscount = 0;
	var totalTotalPrice = 0;
	var totalTotalDiscount = 0;
	
	var totalLandedCost = 0;
	
	$( "[id='DeliveryCost']" ).each(function( index, element  ) {
	
	
		var thisQuantity = parseFloat($(this).parent().parent("TR").find("[id='Quantity']").val());
		if (isNaN(thisQuantity))
			thisQuantity = 0;

		
		var thisUnitPrice = parseFloat($(this).parent().parent("TR").find("[id='UnitPrice']").val());
		if (isNaN(thisUnitPrice))
			thisUnitPrice = 0;
		

		$(this).parent().parent("TR").find("[id='TotalPrice']").val(parseFloat(thisQuantity * thisUnitPrice).toFixed(2));
		var thisTotalPrice = parseFloat($(this).parent().parent("TR").find("[id='TotalPrice']").val());
		if (isNaN(thisTotalPrice))
			thisTotalPrice = 0;
		totalTotalPriceXDiscount += thisTotalPrice;

		var thisUnitDiscount = parseFloat($(this).parent().parent("TR").find("[id='UnitDiscount']").val()).toFixed(2);
		var thisUnitDiscountType = $(this).parent().parent("TR").find("[id='UnitDiscountType']").val();
		var thisDiscountAmount = 0;
		if (thisUnitDiscountType == "%" && !isNaN(thisUnitDiscount))
		{
			thisDiscountAmount = parseFloat((thisTotalPrice * thisUnitDiscount) / 100);
			thisTotalPrice = thisTotalPrice - thisDiscountAmount;
		}else if (thisUnitDiscountType == "$" && !isNaN(thisUnitDiscount)){
			thisDiscountAmount = parseFloat(thisUnitDiscount);
			thisTotalPrice = thisTotalPrice - thisUnitDiscount;
		}			
		$(this).parent().parent("TR").find("[id='TotalPrice']").val(parseFloat(thisTotalPrice).toFixed(2));
			
			
		// $(this).parent().parent("TR").find("[id='TotalItemPrice']").val(parseFloat(thisQuantity * thisUnitPrice).toFixed(2));
		var Multiplier = parseFloat($('#Multiplier').val());
		$(this).parent().parent("TR").find("[id='TotalItemPrice']").val(parseFloat(thisTotalPrice * Multiplier).toFixed(2));
		
		var thisTotalItemPrice = parseFloat($(this).parent().parent("TR").find("[id='TotalItemPrice']").val());
		if (isNaN(thisTotalItemPrice))
			thisTotalItemPrice = 0;
			
			
			
		var thisTaxCost = parseFloat($(this).parent().parent("TR").find("[id='TaxCost']").val());
		if (isNaN(thisTaxCost))
			thisTaxCost = 0;			
			
		//alert(PODeliveryCost);	
		var thisDeliveryCost = ((thisTotalItemPrice) / $('#ProductCostRM').val()) * PODeliveryCost;
		//alert(DeliveryPercentage);
		if (isNaN(thisDeliveryCost))
			thisDeliveryCost = 0;	
		if (thisDeliveryCost > 0)
			element.value = (parseFloat(thisDeliveryCost).toFixed(2));	
	
		//alert(thisTotalItemPrice + " || " + thisDeliveryCost+ " || " + thisTaxCost);
		var thisLandedCost = parseFloat(thisTotalItemPrice) + parseFloat(thisDeliveryCost) + parseFloat(thisTaxCost);
		$(this).parent().parent("TR").find("[id='LandedCost']").val(parseFloat(thisLandedCost).toFixed(2));
		
		var thisUnitLandedCost = (parseFloat(thisTotalItemPrice) + parseFloat(thisDeliveryCost) + parseFloat(thisTaxCost)) / thisQuantity;
		if (isNaN(thisUnitLandedCost))
			thisUnitLandedCost = 0;			
		
		$(this).parent().parent("TR").find("[id='UnitLandedCost']").val(parseFloat(thisUnitLandedCost).toFixed(2));

		var thisMarkup = parseFloat($(this).parent().parent("TR").find("[id='UnitMarkup']").val());
		<? 
		$systemSetting = new Zend_Session_Namespace('systemSetting');	
		if ($systemSetting->markup_type == "MARKUP") { 
		?>
			var thisUnitRetail = ((thisMarkup / 100) * thisUnitLandedCost) + thisUnitLandedCost;
		<? } else if ($systemSetting->markup_type == "GROSS_MARGIN") { ?>
			if (parseInt(thisMarkup) >= 100){
				var thisUnitRetail = "0";
				$(this).parent().parent("TR").find("[id='UnitMarkup']").css("color","red");
				$(this).parent().parent("TR").find("[id='UnitMarkup']").poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Invalid Gross Margin")?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
				$(this).parent().parent("TR").find("[id='UnitMarkup']").poshytip('show');
			}else{
				var thisUnitRetail = thisUnitLandedCost / ((100-thisMarkup) / 100); //    ((thisMarkup / 100) * thisUnitLandedCost) + thisUnitLandedCost;
				$(this).parent().parent("TR").find("[id='UnitMarkup']").css("color","black");

			
			}
		<? } else { ?>
			var thisUnitRetail = thisUnitLandedCost;
		<? } ?>
		
		if (isNaN(thisUnitRetail))
			$(this).parent().parent("TR").find("[id='UnitRetail']").val(parseFloat(thisUnitLandedCost).toFixed(2));
		else
			$(this).parent().parent("TR").find("[id='UnitRetail']").val(parseFloat(thisUnitRetail).toFixed(2));
		
		totalQuantity += thisQuantity;
		totalUnitPrice += thisUnitPrice;
		totalTotalPrice += thisTotalPrice;
		totalTaxCost += thisTaxCost;
		totalDeliveryCost += thisDeliveryCost;
		totalTotalItemPrice += thisTotalItemPrice;
		totalLandedCost += thisLandedCost;
		totalTotalDiscount += thisDiscountAmount;
		
		//$(this).parent().parent("TR").find("[id='LandedCost']").val(parseFloat(totalLandedCost).toFixed(2));
		
	});
	
	
	$( "[id='TotalQuantity']" ).val(totalQuantity);
	$( "[id='TotalUnitPrice']" ).val(parseFloat(totalUnitPrice).toFixed(2));
	$( "[id='TotalTotalItemPrice']" ).val(parseFloat(totalTotalItemPrice).toFixed(2));
	
	$( "[id='ProductCostXDiscount']" ).val(parseFloat(totalTotalPriceXDiscount).toFixed(2));
	
	if (totalTotalPrice > 0)
		$( "[id='TotalTotalPrice']" ).val(parseFloat(totalTotalPrice).toFixed(2));
	else
		$( "[id='TotalTotalPrice']" ).val("");

	if (totalTotalPrice > 0)
		$( "[id='ProductCost']" ).val(parseFloat(totalTotalPrice).toFixed(2));
	else
		$( "[id='ProductCost']" ).val("");
	
	if (totalDeliveryCost > 0)
		$( "[id='TotalDeliveryCost']" ).val(parseFloat(totalDeliveryCost).toFixed(2));
	else
		$( "[id='TotalDeliveryCost']" ).val("");
	
	if (totalTaxCost > 0)
		$( "[id='TotalTaxCost']" ).val(parseFloat(totalTaxCost).toFixed(2));
	else
		$( "[id='TotalTaxCost']" ).val("");

	if (totalTaxCost > 0)
		$( "[id='POTaxCost']" ).val(parseFloat(totalTaxCost).toFixed(2));
	else
		$( "[id='POTaxCost']" ).val("");

	if (totalTotalDiscount > 0)	
		$("#PODiscount").val(parseFloat(totalTotalDiscount).toFixed(2));
	else
		$("#PODiscount").val("");
	
	if (totalTotalDiscount > 0)	
		$( "#TotalDiscount" ).val(parseFloat(totalTotalDiscount).toFixed(2));
	else	
		$( "#TotalDiscount" ).val("");
	
	CalculateRMConvert();
	CalculateFinalCosting();
	
	$( "[id='TotalLandedCost']" ).val(parseFloat(totalLandedCost).toFixed(2));	



}


$(document).ready(function() {
var loading = true;
<?=$this->ddSelectjs?>
loading = false;
 
 $( "#PurchaseDate" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
 $( "#ExpectedDate" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
 $( "#OADate" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
 $( "#ReceivedDate" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
 $( "#StatusDateOverall" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
 
 
 	$( "[idx='StatusDate']" ).each(function( index, element  ) {
	
		$( element ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
 
	});	
 
 

$('#POFile').poshytip({ className: 'tip-yellow', showOn: 'hover', alignTo: 'target',offsetY: 10, offsetX: 1, alignX: 'inner-left', showTimeout: 100});
$('#AOFile').poshytip({ className: 'tip-yellow', showOn: 'hover', alignTo: 'target',offsetY: 10, offsetX: 1, alignX: 'inner-left', showTimeout: 100});
$('#OrderNumber').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#PurchaseDate').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#ProductCost').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#PODeliveryCost').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
//$('#MiscCost').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#MiscNote').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#TotalCost').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});

$('#POTaxCost').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#ProductCostFromItems').poshytip({ className: 'tip-yellow', showOn: 'hover', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#ProductCostFromItemsDiff').poshytip({ className: 'tip-yellow', showOn: 'hover', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});

$('#ActualCost').poshytip({ className: 'tip-yellow', showOn: 'hover', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#UpdateSerialNumber').poshytip({ className: 'tip-yellow', showOn: 'hover', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});


$('#search_item').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#clear').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#add_item').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#save_item').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#remove_image').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});

$('#qUpdateStatus').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});


if ($('#POStatus').val() == "received")
{
	$('#idReceivedDate').show();
}

ResetItemNumbers();
CalculateAverageAdditional();
CalculateDifference();


$('#save_po').click(function () {
	return SavePO();
})
$('#save_po2').click(function () {
	return SavePO();
})
	
$('#create_po').click(function () {
	return SavePO();			
	
})
<? if ($this->edit_po) {?>
$('#unlock_po').click(function () {
	

	var stateslock = {
		state0:  {
			title: '<?=$this->translate->_("Enter system password")?>.',
			html:'<?=$this->translate->_("Please enter your system password to un lock the PO")?><BR>'+
				'<label><B><?=$this->translate->_("Password")?>:</B> <input type="Password" name="Password" value=""></label><br />',
			buttons: { Save: true, Cancel: false },
			submit:function(e,v,m,f){ 
				if (v)
				{
					 $.post("/inventory/po/ajaxunlockpo",{ID:"<?=$this->userInfo->ID?>", Password:f['Password'], POID:<?=$this->edit_po?>},function(result){
						
						
						if(!parseInt(result)){
							console.log("asdasd");
							e.preventDefault();
							$.prompt.goToState('state1');
							return false;
						}else{
							$.prompt.close();
							document.location='/inventory/po/index/edit_po/<?=$this->edit_po?>/'
							
						}	
					 });
					
				}
				else
					$.prompt.close();
				return false;
			
			}
		},
		state1: {
			title: '<?=$this->translate->_("Enter system password")?>.',
			html:'<?=$this->translate->_("Your password is not correct")?>. ',
			buttons: { Back: -1, Exit: 0 },
			focus: 1,
			submit:function(e,v,m,f){
				e.preventDefault();
				if(v==0)
					$.prompt.close();
				else if(v==-1)
					$.prompt.goToState('state0');
			}
		},
	};

	$.prompt(stateslock);		

	return false;
})


$('#lock_po').click(function () {
	
	if (SavePO())
	{
		var stateslock = {
			state0:  {
				title: '<?=$this->translate->_("Enter system password")?>.',
				html:'<?=$this->translate->_("Please enter your system password to lock the PO")?><BR>'+
					'<label><B><?=$this->translate->_("Password")?>:</B> <input type="Password" name="Password" value=""></label><br />',
				buttons: { Save: true, Cancel: false },
				submit:function(e,v,m,f){ 
					if (v)
					{
						 $.post("/inventory/po/ajaxlockpo",{ID:"<?=$this->userInfo->ID?>", Password:f['Password'], POID:<?=$this->edit_po?>},function(result){
							
							
							if(!parseInt(result)){
								console.log("asdasd");
								e.preventDefault();
								$.prompt.goToState('state1');
								return false;
							}else{
								$.prompt.close();
								document.location='/inventory/po/index/edit_po/<?=$this->edit_po?>/'
								
							}	
						 });
						
					}
					else
						$.prompt.close();
					return false;
				
				}
			},
			state1: {
				title: '<?=$this->translate->_("Enter system password")?>.',
				html:'<?=$this->translate->_("Your password is not correct")?>. ',
				buttons: { Back: -1, Exit: 0 },
				focus: 1,
				submit:function(e,v,m,f){
					e.preventDefault();
					if(v==0)
						$.prompt.close();
					else if(v==-1)
						$.prompt.goToState('state0');
				}
			},
		};

		$.prompt(stateslock);		
	}
	return false;
})
<? } ?>	

	
	

$('#ProductCost').change(function () {
	CalculateFinalCosting();
	CalculateDifference();
})

$('#PODeliveryCost').change(function () {
	CalculateFinalCosting();
	CalculateDifference();
	CalculateAverageAdditional();
})

$('#POTaxCost').change(function () {
	CalculateFinalCosting();
	CalculateDifference();
	CalculateAverageAdditional();
})

$('#TotalTotalPrice').mouseover(function () {
	$('#TotalTotalPrice').css("border", "solid 1px #45EF45");
	$('#ProductCost').css("border", "solid 1px #45EF45");
})
$('#TotalTotalPrice').mouseout(function () {
	$('#TotalTotalPrice').css("border", "solid 1px #ccc");
	$('#ProductCost').css("border", "solid 1px #ccc");
})

$('#ProductCost').mouseover(function () {
	$('#TotalTotalPrice').css("border", "solid 1px #45EF45");
	$('#ProductCost').css("border", "solid 1px #45EF45");
})
$('#ProductCost').mouseout(function () {
	$('#TotalTotalPrice').css("border", "solid 1px #ccc");
	$('#ProductCost').css("border", "solid 1px #ccc");
})




$('#PODiscount').mouseover(function () {
	$('#PODiscount').css("border", "solid 1px #45EF45");
	$('#TotalDiscount').css("border", "solid 1px #45EF45");
})
$('#PODiscount').mouseout(function () {
	$('#PODiscount').css("border", "solid 1px #ccc");
	$('#TotalDiscount').css("border", "solid 1px #ccc");
})

$('#TotalDiscount').mouseover(function () {
	$('#TotalDiscount').css("border", "solid 1px #45EF45");
	$('#PODiscount').css("border", "solid 1px #45EF45");
})
$('#TotalDiscount').mouseout(function () {
	$('#TotalDiscount').css("border", "solid 1px #ccc");
	$('#PODiscount').css("border", "solid 1px #ccc");
})


$('#ProductCostRM').mouseover(function () {
	$('#ProductCostRM').css("border", "solid 1px #45EF45");
	$('#TotalTotalItemPrice').css("border", "solid 1px #45EF45");
})
$('#ProductCostRM').mouseout(function () {
	$('#ProductCostRM').css("border", "solid 1px #ccc");
	$('#TotalTotalItemPrice').css("border", "solid 1px #ccc");
})

$('#TotalTotalItemPrice').mouseover(function () {
	$('#TotalTotalItemPrice').css("border", "solid 1px #45EF45");
	$('#ProductCostRM').css("border", "solid 1px #45EF45");
})
$('#TotalTotalItemPrice').mouseout(function () {
	$('#TotalTotalItemPrice').css("border", "solid 1px #ccc");
	$('#ProductCostRM').css("border", "solid 1px #ccc");
})

//////////////////////////////////////////////////////////////////////
$('#TotalDeliveryCost').mouseover(function () {
	$('#TotalDeliveryCost').css("border", "solid 1px #45EF45");
	$('#PODeliveryCost').css("border", "solid 1px #45EF45");
})
$('#TotalDeliveryCost').mouseout(function () {
	$('#TotalDeliveryCost').css("border", "solid 1px #ccc");
	$('#PODeliveryCost').css("border", "solid 1px #ccc");
})

$('#PODeliveryCost').mouseover(function () {
	$('#PODeliveryCost').css("border", "solid 1px #45EF45");
	$('#TotalDeliveryCost').css("border", "solid 1px #45EF45");
})
$('#PODeliveryCost').mouseout(function () {
	$('#PODeliveryCost').css("border", "solid 1px #ccc");
	$('#TotalDeliveryCost').css("border", "solid 1px #ccc");
})


//////////////////////////////////////////////////////////////////////
$('#TotalTaxCost').mouseover(function () {
	$('#TotalTaxCost').css("border", "solid 1px #45EF45");
	$('#POTaxCost').css("border", "solid 1px #45EF45");
})
$('#TotalTaxCost').mouseout(function () {
	$('#TotalTaxCost').css("border", "solid 1px #ccc");
	$('#POTaxCost').css("border", "solid 1px #ccc");
})

$('#POTaxCost').mouseover(function () {
	$('#POTaxCost').css("border", "solid 1px #45EF45");
	$('#TotalTaxCost').css("border", "solid 1px #45EF45");
})
$('#POTaxCost').mouseout(function () {
	$('#POTaxCost').css("border", "solid 1px #ccc");
	$('#TotalTaxCost').css("border", "solid 1px #ccc");
})


//////////////////////////////////////////////////////////////////////
$('#TotalLandedCost').mouseover(function () {
	$('#TotalLandedCost').css("border", "solid 1px #45EF45");
	$('#TotalCost').css("border", "solid 1px #45EF45");
})
$('#TotalLandedCost').mouseout(function () {
	$('#TotalLandedCost').css("border", "solid 1px #ccc");
	$('#TotalCost').css("border", "solid 1px #ccc");
})

$('#TotalCost').mouseover(function () {
	$('#TotalCost').css("border", "solid 1px #45EF45");
	$('#TotalLandedCost').css("border", "solid 1px #45EF45");
})
$('#TotalCost').mouseout(function () {
	$('#TotalCost').css("border", "solid 1px #ccc");
	$('#TotalLandedCost').css("border", "solid 1px #ccc");
})

// Calculating Currency Multiplier //
$('#Currency').change(function () {
	CalculateRMConvert();
	$( "[id='ItemCurrency']" ).each(function( index, element  ) {
		element.innerHTML = $('#Currency').val()+": ";

	});	
	$( "[id='ItemCurrencyHeader']" ).each(function( index, element  ) {
		$(element).html("("+$('#Currency').val()+")");
	});	

	$( "[id='LabelCurrency']" ).each(function( index, element  ) {
		$(element).html($('#Currency').val());
	});	
	
	// get real time exchange rate
	$.get("/admin/system/ajaxgetcurrency",{TargetCurrency:$('#Currency').val()},function(result){
		$('#Multiplier').val(result);
		CalculateRMConvert();
		CalculateAverageAdditional();	
	});	
	
	
	
	
})



if ($('#Multiplier').val() == ""){
	$.get("/admin/system/ajaxgetcurrency",{TargetCurrency:$('#Currency').val()},function(result){
		$('#Multiplier').val(result);
		CalculateRMConvert();
		CalculateAverageAdditional();	
	});	
}

$('#Multiplier').change(function () {
	CalculateRMConvert();
	CalculateAverageAdditional();
})
$('#ProductCost').change(function () {
	CalculateRMConvert();
	CalculateAverageAdditional();
})
// Calculating Currency Multiplier //
	
	
	
	

var i = $('#report_table TR').size() + 1;

$('#AddItems').click(function () {
		
	$.ajaxSetup({ cache: false });
	$.get( "/inventory/po/ajaxadditem/orderid/<?=$this->edit_po?>", function( data ) {
		$('#report_table_footer').before(data); 
		
		ResetItemNumbers();
		CalculateAverageAdditional();

		$( "[idx='StatusDate']" ).each(function( index, element  ) {
		
			$( element ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});
	 
		});			
	});
	//$('#report_table').append("<TR class='report_even'><TD class='report_cell'  style='text-align:center'>1</TD><TD class='report_cell'  style='text-align:center'>7</TD><TD class='report_cell'  style='text-align:center'><img src='/uploads/ItemImage/small/7.jpg'></TD><TD class='report_cell'  style='text-align:left'>Applied Analytics</TD><TD class='report_cell'  style='text-align:left'>TLG 837 Tail Gas Analyzer</TD><TD class='report_cell'  style='text-align:left'>TLG 837</TD><TD class='report_cell'  style='text-align:left'>&nbsp</TD><TD class='report_cell'  style='text-align:right'>RM 12.45</TD><TD class='report_cell'  style='text-align:center'><img border=0 src='/images/icons/IconDelete.gif' id='RemoveRow' name='RemoveRow'></TD></TR>");
	
})
	
	<? if ($this->edit_po)  { ?>
	$('#CancelChanges').click(function () {
		document.location = "/inventory/po/index/edit_po/"+<?=$this->edit_po?>;
	})	
	$('#CancelChanges2').click(function () {
		document.location = "/inventory/po/index/edit_po/"+<?=$this->edit_po?>;
	})		
	
	<? } ?>
	
	
	$(document).on("change", "#UnitPrice", function(){	
		CalculateDifference();
	})
	
	$(document).on("change", "#TaxCost", function(){
			
		CalculateDifference();
	})
		
	$(document).on("change", "#Quantity", function(){	
		CalculateDifference();
	})
	
	$(document).on("change", "#UnitMarkup", function(){	
		CalculateDifference();
	})
	
	$(document).on("change", "#UnitDiscount", function(){	
		CalculateDifference();
	})
	
	$(document).on("change", "#UnitDiscountType", function(){	
		if ($(this).val() == "")
		{
			$(this).parent().parent("TR").find("[id='UnitDiscount']").val("");	
		}
		CalculateDifference();
	})	
	
//	$(document).on("change", "#ItemID", function(){	
//		var counter = 0; var selectedID = $(this).val();
//		$( "[id='ItemID']" ).each(function( index, element  ) {
//			if (selectedID == element.value){
//				counter += 1;
//			}
//		});	
//		
//		if (counter > 1){
//			$.prompt("The selected item already exist in the list.",{ title: "Invalid Entry", buttons: { Ok: true }});
//			$(this).val("");
//			$(this).css("border", "1px solid red");
//		}
//		return false;
//	})
	
	
	
	
	$(document).on("click", "#RemoveRowConfirm", function(){	
	
		var thisPOItemsID = $(this).parent().parent("TR").find("[id='POItemsID']").val();
		var thisObj = $(this).parents("TR");

		$.prompt(
		"<?=$this->translate->_('Are you sure you want to remove this item?<BR>Any serial number entered for these items will be removed as well.')?>",{
		buttons: { Ok: true, Cancel: false },
		submit:function(e,v,m,f){ 
			if(v){
				$.ajaxSetup({ cache: false });
				$.get( "/inventory/po/ajaxremovepoitems/poitemsid/"+thisPOItemsID, function( data ) {

					thisObj.remove();
					
					$( "[id='itemcounter']" ).each(function( index, element  ) {
						element.innerHTML = (index + 1);
					});
					
					if (!isNaN(parseFloat($('#PODeliveryCost').val()))){
						PODeliveryCost = parseFloat($('#PODeliveryCost').val());
					}
						
					if (!isNaN(parseFloat($('#POTaxCost').val()))){
						POTaxCost = parseFloat($('#POTaxCost').val());
					}
					var totalSize = $( "[id='CostPrice']" ).size();
					var totalAdditional = PODeliveryCost + POTaxCost;			
					var averageAdditional = parseFloat(totalAdditional / totalSize).toFixed(2);
					$( "[id='CostPrice']" ).each(function( index, element  ) {
						element.value = (averageAdditional);
					});
					
					CalculateDifference();
					CalculateAverageAdditional();							
					
				});						
			}
		}
	  
		});
	});
	
	
	$(document).on("click", "#RemoveRow", function(){	
	
		var thisPOItemsID = $(this).parent().parent("TR").find("[id='POItemsID']").val();
		var thisObj = $(this).parents("TR");

		$.ajaxSetup({ cache: false });
		$.get( "/inventory/po/ajaxremovepoitems/poitemsid/"+thisPOItemsID, function( data ) {

			thisObj.remove();
			
			$( "[id='itemcounter']" ).each(function( index, element  ) {
				element.innerHTML = (index + 1);
			});
			
			if (!isNaN(parseFloat($('#PODeliveryCost').val()))){
				PODeliveryCost = parseFloat($('#PODeliveryCost').val());
			}
				
			if (!isNaN(parseFloat($('#POTaxCost').val()))){
				POTaxCost = parseFloat($('#POTaxCost').val());
			}
			var totalSize = $( "[id='CostPrice']" ).size();
			var totalAdditional = PODeliveryCost + POTaxCost;			
			var averageAdditional = parseFloat(totalAdditional / totalSize).toFixed(2);
			$( "[id='CostPrice']" ).each(function( index, element  ) {
				element.value = (averageAdditional);
			});
			
			CalculateDifference();
			CalculateAverageAdditional();							
			
		});						

	});
				
	$( "#dialog-message" ).dialog({
	   autoOpen: false,
	   modal: true,
	   width: '600',
	   height: '450',
        buttons: {
          'Close': function() {
            $(this).dialog('close');
				$.get( "/admin/system/getbranches/", function( data ) {
					  $( "#BranchID" ).html(data);
				}, "html");			
          }
		 }
	  
	});	

	$('#BranchID').change(function () {
		if (($(this).val() == "add-new"))
		{
			  $.ajaxSetup({
					// Disable caching of AJAX responses
					cache: false
				});

				$( "#dialog-message" ).dialog("open");
				$( "#dialog-message" ).html("<img src='/images/icons/IconIndicator.gif'>");
				$.get( "/admin/system/addbranches/", function( data ) {
					 $( "#dialog-message" ).html(data);
					   
					  
				}, "html");
		}
	
	})	

	$('#POStatus').change(function () {
		if ($('#POStatus').val() == "received")
			$('#idReceivedDate').show();
		else
			$('#idReceivedDate').hide();

	
	})	
	
	$('#ReceivedDate').change(function () {
		$('#StatusDateOverall').val($('#ReceivedDate').val());
	})	
		
	$('#StatusDateOverall').change(function () {
		$( "[idx='StatusDate']" ).each(function( index, element  ) {
			$( element ).val($('#StatusDateOverall').val());
		});	
	})	
					
	$( "#dialog-message-vendor" ).dialog({
	   autoOpen: false,
	   modal: true,
	   width: '600',
	   height: '450',
        buttons: {
          'Close': function() {
            $(this).dialog('close');
				$.get( "/admin/system/getvendors/", function( data ) {
					  $( "#VendorID" ).html(data);
				}, "html");			
          }
		 }
	  
	});	

	$('#VendorID').change(function () {
		if (($(this).val() == "add-new"))
		{
			  $.ajaxSetup({
					// Disable caching of AJAX responses
					cache: false
				});

				$( "#dialog-message-vendor" ).dialog("open");
				$( "#dialog-message-vendor" ).html("<img src='/images/icons/IconIndicator.gif'>");
				$.get( "/admin/system/addvendors/", function( data ) {
					 $( "#dialog-message-vendor" ).html(data);
					   
					  
				}, "html");
		}
	
	})


	$(document).on("change", "#ItemID", function(){	
	
		
		if (($(this).val() == "add-new"))
		{
		
			  var objItems = $(this);
			  $.ajaxSetup({
					// Disable caching of AJAX responses
					cache: false
				});

				$( "#dialog-message-items" ).dialog({
				   autoOpen: false,
				   modal: true,
				   width: '600',
				   height: '450',
					buttons: {
					  'Close': function() {
						$(this).dialog('close');
							$.get( "/inventory/brand/getitem/", function( data ) {
								  objItems.html(data);
							}, "html");			
					  }
					 }
				  
				});						
				

				$( "#dialog-message-items" ).dialog("open");
				$( "#dialog-message-items" ).html("<img src='/images/icons/IconIndicator.gif'>");
				$.get( "/inventory/brand/additem/", function( data ) {
					console.log(data);
					 $( "#dialog-message-items" ).html(data);
					   
					  
				}, "html");
		}
	})	
	$(document).on("change", "#StatusOverall", function(){	
	
		var selectedIndex = $(this).prop("selectedIndex");
		
		$( "[id='Status']" ).each(function( index, element  ) {
			element.selectedIndex = selectedIndex;
		});
	
	})
	
	
	
	$(document).on("change", "#POStatus", function(){	
	
		if ($(this).val() == "received")
		{	
			$("#StatusOverall").prop("selectedIndex", 1);
			$("#StatusOverall").trigger("change");

		}else if ($(this).val() == "process")
		{	
			$("#StatusOverall").prop("selectedIndex", 5); //indent
			$("#StatusOverall").trigger("change");
		}
		
		$( "[id='StatusCheck']" ).each(function( index, element  ) {
				$(element).prop("checked", true);
		});
		$("#StatusCheckOverall").prop("checked", true); 
		
		
	})
	
	
	$(document).on("click", "#StatusCheckOverall", function(){	
	
		if ($(this).prop("checked"))
		{
			$( "[id='StatusCheck']" ).each(function( index, element  ) {
				$(element).prop("checked", true);
			});	
		}else
		{
			$( "[id='StatusCheck']" ).each(function( index, element  ) {
				$(element).prop("checked", false);
			});	
		}
	})	
	
	
	
});	





</script>

<div id="dialog-message" title="<?=$this->translate->_('Add New Branch')?>"></div>
<div id="dialog-message-vendor" title="<?=$this->translate->_('Add New Vendor')?>"></div>
<div id="dialog-message-items" title="<?=$this->translate->_('Add New Items')?>"></div>

<B class='PageHeader'><?=$this->translate->_('Purchase Orders')?></B><BR>


<script>
function OnSelectItem(obj, itemIndex, poitemId)
{
	console.log(obj);
	if (obj.selectedData.value == "add-new")
	{
	
		 //var objItems = $(this);
		  var objItems = $(obj.selectedData);
		  $.ajaxSetup({
				// Disable caching of AJAX responses
				cache: false
			});

			$( "#dialog-message-items" ).dialog({
			   autoOpen: false,
			   modal: true,
			   width: '600',
			   height: '450',
				buttons: {
				  'Close': function() {
					$(this).dialog('close');
						//document.location='/inventory/po/index/edit_po/<?=$this->edit_po?>';
						
						$.get( "/inventory/brand/getitemex/", function( data ) {
							
							$("#divSelect_"+itemIndex).html("<SELECT  Name='ItemID[]' ID='ItemID'  class=\"Item_"+poitemId+"\">"+data+"</SELECT>")
							$('.Item_'+poitemId).ddslick({ 
								'width':'450px', 
								onSelected: function(selectedData)
								{
									OnSelectItem(selectedData, itemIndex, poitemId) 
								}
							});
							
								
						//objItems.html(data);
						}, "html");			
				  }
				 }
			  
			});						
			

			$( "#dialog-message-items" ).dialog("open");
			$( "#dialog-message-items" ).html("<img src='/images/icons/IconIndicator.gif'>");
			$.get( "/inventory/brand/additem/", function( data ) {
				
				 $( "#dialog-message-items" ).html(data);
				   
				  
			}, "html");
	}else
	{
		$( "[name='ItemID["+itemIndex+"]']" ).val(obj.selectedData.value);
	}	
	
	
	
}

</script>
<style>
.dd-select {
	width: 400px;
}
.dd-container {
	width: 400px;
}
.dd-options {
	height: 400px;
}

.dd-option:hover {
	text-decoration: none;
}

.dd-option {
	padding:2px 10px;
}
.dd-selected {
	padding:2px 10px;
}

.dd-selected:hover {
	text-decoration: none;
}
</style>
<script type="text/javascript" src="/js/jquery/ddslick/ddslick.js"></script>


<form enctype="multipart/form-data"  action='/inventory/po' method=POST>
	<table border=0 cellspacing=2 cellpadding=2>
	
	<?
	$systemSetting = new Zend_Session_Namespace('systemSetting');
	if ($this->POFilePath){
		$strFilePO = "<a target='_new' href='".$this->POFilePath."'><img border=0 src='/images/icons/IconView.png'></a>&nbsp;&nbsp;&nbsp;";
	}
	if ($this->AOFilePath){
		$strFileAO = "<a target='_new' href='".$this->AOFilePath."'><img border=0 src='/images/icons/IconView.png'></a>&nbsp;&nbsp;&nbsp;";
	}
	
	
	if ($systemSetting->userInfo->ACLRole != "User" && $systemSetting->userInfo->ACLRole != "Sales" && $systemSetting->userInfo->ACLRole != "Account")
	{
			if ($this->POFilePath){
				$strFilePO .= "<input type=submit name='remove_file_po' id='remove_file' value='".$this->translate->_('Remove File')."' title='".$this->translate->_('Click to remove the PO document. Select a differnt file to replacement existing one').".'>";
			}
			if ($this->AOFilePath){
				$strFileAO .= "<input type=submit name='remove_file_ao' id='remove_file' value='".$this->translate->_('Remove File')."' title='".$this->translate->_('Click to remove the Order Acknowledgement document. Select a differnt file to replacement existing one').".'>";
			}	

			$strFilePO .= "<BR><input type='file' name='POFile' id='POFile' size='35' title='".$this->translate->_('The file must be less than or equal to 1MB in size')."'>";
			$strFileAO .= "<BR><input type='file' name='AOFile' id='AOFile' size='35' title='".$this->translate->_('The file must be less than or equal to 1MB in size')."'>";

		
	}
	
	?>
		<TR><TD class='form_label' width=200px><?=$this->translate->_('PO Document')?></TD><TD  class='form_field' valign=bottom>
		<?=$strFilePO?></TD></TR>
		<TR><TD class='form_label' ><?=$this->translate->_('Order Acknowledgement')?></TD><TD  class='form_field' valign=bottom>
		<?=$strFileAO?></TD></TR>
		<TR><TD class='form_label' ><?=$this->translate->_('Order Number')?><font class='required'>*</font></TD><TD class='form_field'><input <?=$this->disabled?> type='text' name='OrderNumber' id='OrderNumber' size="35" value='<?=$this->OrderNumber?>' title="<?=$this->translate->_('Purchase order number')?>."></TD></TR>
		<TR><TD class='form_label' ><?=$this->translate->_('Branch')?><font class='required'>*</font></TD><TD class='form_field' valign=bottom> <select <?=$this->disabled?> name='BranchID' id='BranchID' title=""><option value=''>-</option><?=$this->optionBranches?><option value='add-new'><<< <?=$this->translate->_('ADD NEW')?> >>></option></select></TD></TR>
		<TR><TD class='form_label' ><?=$this->translate->_('Vendor')?><font class='required'>*</font></TD><TD class='form_field' valign=bottom> <select <?=$this->disabled?> name='VendorID' id='VendorID' title=""><option value=''>-</option><?=$this->optionVendors?><option value='add-new'><<< <?=$this->translate->_('ADD NEW')?> >>></option></select></TD></TR>
		<TR><TD class='form_label' ><?=$this->translate->_('Purchase Date')?></TD><TD class='form_field'><input type='text' <?=$this->disabled?> name='PurchaseDate' id='PurchaseDate' size="10" value='<?=$this->PurchaseDate?>' title="<?=$this->translate->_("Purchase order date")?>."></TD></TR>
		
		<TR><TD class='form_label' ><?=$this->translate->_('Order Acknowledgement Date')?></TD><TD class='form_field'><input type='text' <?=$this->disabled?> name='OADate' id='OADate' size="10" value='<?=$this->OADate?>' title="<?=$this->translate->_("Order Acknowledment date")?>."></TD></TR>
		<TR><TD class='form_label' ><?=$this->translate->_('Expected Date')?></TD><TD class='form_field'><input type='text' <?=$this->disabled?> name='ExpectedDate' id='ExpectedDate' size="10" value='<?=$this->ExpectedDate?>' title="<?=$this->translate->_("Expected delivery date")?>."></TD></TR>
		
		
		<TR><TD class='form_label' ><?=$this->translate->_('Currency')?></TD><TD class='form_field'>
		<SELECT <?=$this->disabled?> Name="Currency" ID="Currency"><?=$this->optionCurrency?></select>x <input <?=$this->disabled?> size=5 type="text" name="Multiplier" id="Multiplier" value="<?=$this->Multiplier?>"> 
		</TD></TR>
		<TR><TD class='form_label' ><?=$this->translate->_('Product Cost')?></TD><TD class='form_field'><div  style='float:left;' id="LabelCurrency"><?=$this->Currency?></div>:  <input style='text-align:right' type='text' readonly <?=$this->disabled?> name='ProductCostXDiscount' id='ProductCostXDiscount'  size="10" value='<?=$this->ProductCostXDiscount?>' title="<?=$this->translate->_("Purchase order's total product / item cost. Not include transport or misc charges")?>.">
		<TR><TD class='form_label' ><?=$this->translate->_('Total Discount')?></TD><TD class='form_field'><div  style='float:left;' id="LabelCurrency"><?=$this->Currency?></div>:  <input  style='text-align:right;' readonly <?=$this->disabled?> readonly type='text' name='PODiscount' id='PODiscount'  size="10" value='<?=$this->PODiscount?>' title="<?=$this->translate->_("Total discounts given")?>.">
		<TR><TD class='form_label' ><?=$this->translate->_('Final Product Cost')?></TD><TD class='form_field'><div  style='float:left;' id="LabelCurrency"><?=$this->Currency?></div>:  <input style='text-align:right' type='text' readonly <?=$this->disabled?> name='ProductCost' id='ProductCost'  size="10" value='<?=$this->ProductCost?>' title="<?=$this->translate->_("Purchase order's total product / item cost. Not include transport or misc charges")?>.">
		<TR><TD class='form_label' ><?=$this->translate->_('Product Cost')?></TD><TD class='form_field'><?=$this->currencyType?>: <input readonly size=10 style='text-align:right' type="text" name="ProductCostRM" id="ProductCostRM" value="<?=$this->ProductCostRM?>">
		
	<!--	<TR><TD class='form_label' ><?=$this->translate->_('Freight Forwarder')?></TD><TD class='form_field'></TD></TR> -->
		<TR><TD class='form_label' ><?=$this->translate->_('Delivery Cost')?></TD><TD class='form_field'><?=$this->currencyType?>: <input <?=$this->disabled?> style='text-align:right' type='text' name='PODeliveryCost' id='PODeliveryCost'  size="10" value='<?=$this->PODeliveryCost?>' title="<?=$this->translate->_("Purchase order's misc charges")?>.">
		<input placeholder="<?=$this->translate->_('Freight Forwarder Code')?>" <?=$this->disabled?> type='text' name='FreightForwarder' id='FreightForwarder'  size="30" value='<?=$this->FreightForwarder?>' title="<?=$this->translate->_("Freight forwarding code")?>.">
		
		</TD></TR>
		<TR><TD class='form_label' ><?=$this->translate->_('Total Tax')?></TD><TD class='form_field'><?=$this->currencyType?>: <input <?=$this->disabled?> readonly style='text-align:right' type='text' name='POTaxCost' id='POTaxCost'  size="10" value='<?=$this->POTaxCost?>' title="<?=$this->translate->_("Total tax applied to all the items")?>.">
		*Total Tax is calculated based on each individual's item tax.
		<!--RM: <input readonly style='text-align:right' type='text' name='TotalTaxCost' id='TotalTaxCost'  size="8" value='' title="Total tax cost.">
		<input readonly style='text-align:right' type='text' name='TotalTaxCostDiff' id='TotalTaxCostDiff'  size="8" value='' title="Total tax cost.">
		-->
		</TD></TR>
		
		<TR><TD class='form_label' ><?=$this->translate->_('Total Costing')?></TD><TD class='form_field'><?=$this->currencyType?>: <input <?=$this->disabled?> style='text-align:right' type='text' readonly name='TotalCost' id='TotalCost'  size="10" value='<?=$this->TotalCost?>' title="<?=$this->translate->_("Purchase order's final / total cost")?>.">
		<TR><TD class='form_label' ><?=$this->translate->_('Order Status')?></TD><TD class='form_field'><SELECT  <?=$this->disabled?>  style='float: left;' name='POStatus' id='POStatus'><?=$this->optionPOStatus?></SELECT> 
		<div id='idReceivedDate' style='display: none; margin-left: 100px; white-space: nowrap; overlow: hidden'>
			<input type='text' <?=$this->disabled?>  placeholder="<?=$this->translate->_('Received Date')?>" name='ReceivedDate' id='ReceivedDate' size=14 value='<?=$this->ReceivedDate?>'>
		</div>
		
		</TD></TR>
		<TR><TD colspan=2 height=10px>
		</TD></TR>
		<TR><TD colspan=2>
		<? if ($this->edit_po && !$this->Locked) { ?>
			<? if ($this->allowEdit) { ?>
			<input type=hidden name='save_po_id' id='save_po_id' value='<?=$this->edit_po?>'>
			<input type=submit name='save_po' id='save_po' value='<?=$this->translate->_('Save Details')?>'>	
			<input type=submit name='lock_po' id='lock_po' value='<?=$this->translate->_('Lock and Finalized')?>'>	
			<input type=button value='Cancel Changes' id='CancelChanges' name='CancelChanges'>
			<? } ?>
			<input type=button value='<?=$this->translate->_('Back to PO Listing')?>' id='Back' name='Back' onclick='document.location="/inventory/po/listing"'>
<BR>
		<? } else if ($this->edit_po && $this->Locked) { ?>
			<?=$this->translate->_("This PO has been locked by")?> <B><?=$this->LockedBy?></B> on <B><?=$this->LockedDate?></B><BR>
			<? if ($this->userInfo->ACLRole == "AdminSystem") {?>
			<input type=submit value='Unlock PO' id='unlock_po' name='unlock_po' value='<?=$this->translate->_('Un-Lock')?>'>
			<? } ?>
			<input type=button value='<?=$this->translate->_('Back to PO Listing')?>' id='Back' name='Back' onclick='document.location="/inventory/po/listing"'>

		<? } else { ?>
			<? if ($this->allowEdit) { ?>
			<input type=submit name='create_po' id='create_po' value='<?=$this->translate->_("Proceed with Purchase Order Items")?>'  title='<?=$this->translate->_("You can PO items after you had created the PO")?>.'>	<BR>
			<div class='small'><?=$this->translate->_("Please fill in the required details before proceeding with purchase items.")?>.</div>
			<? } ?>
		<? } ?>
		
		
		
		
		</TD></TR>
	</table>

<BR><BR>
<? if ($this->edit_po) { ?>
<? if (!$this->Locked && $this->allowEdit) { ?> <input type=button value='Add PO Items' id='AddItems' name='AddItems'> <? } ?>
<? if ($this->allowUpdateMarkup) { ?> 
<input type=submit name='update_markup' id='update_markup' value='<?=$this->translate->_('Save Markup Details')?>'> 
<input type=hidden name='save_po_id' id='save_po_id' value='<?=$this->edit_po?>'> 
<? } ?>
<a name='POItemsList'></a>
<TABLE BORDER=0 align= class='report_table' id='report_table' cellspacing=0 cellpadding=3>
  <TR>
    <TD width=25px nowrap class='report_header' style='text-align:center'>#</TD>
	<TD width=350px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Items")?></TD>
	<TD width=170px nowrap class='report_header' style='text-align:left'><?=$this->translate->_("Status")?> / <?=$this->translate->_("Update")?><img title='<?=$this->translate->_("If the <B>Update</B> is checked, all the individual item units will be updated with the status and the date selected.<BR>Leave the <B>Update</B> un-checked to save the status at the PO level only.")?>' id='qUpdateStatus' src='/images/icons/IconInfo.gif'><BR>
	<SELECT style='font-size:11px; width:100px; float:left;' ID='StatusOverall'><option value=''>-<?=$this->optionStatusItemOverall?></select> <input ID='StatusCheckOverall' type=checkbox>
	<input type=text name='StatusDateOverall' id='StatusDateOverall' size=8 value=''><BR>
	</TD>
	<TD width=75px nowrap class='report_header' style='text-align:center'><?=$this->translate->_("QTY")?></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Unit Price")?><BR><div id="ItemCurrencyHeader" style="text-align:center; margin:0 auto;">(<?=$this->Currency?>)</div></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Discount")?></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Total Price")?><BR><div id="ItemCurrencyHeader" style="text-align:center; margin:0 auto;">(<?=$this->Currency?>)</div></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Total")?><BR>(<?=$this->currencyType?>)</TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Delivery Cost")?><BR>(<?=$this->currencyType?>)</TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Item Tax")?><BR>(<?=$this->currencyType?>)</TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Landed Cost")?><BR>(<?=$this->currencyType?>)</TD>
	<TD width=135px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Unit Landed Cost")?><BR>(<?=$this->currencyType?>)</TD>
	<TD width=135px  nowrap class='report_header' style='text-align:center'><?=$systemSetting->markup_type == "MARKUP" ? $this->translate->_("Unit Markup") : $this->translate->_("Unit Gross Margin")?><BR>(%)</TD>
	<TD width=135px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Unit Retail")?><BR>(<?=$this->currencyType?>)</TD>
	<TD width=40px nowrap class='report_header' style='text-align:center'></TD>
  </TR>
  <?=$this->listItems ?> 
  <TR id="report_table_footer"><TD class='report_even' colspan=113 style='height:2px;'></TD></TR>
  <TR>
    <TD colspan=2 nowrap class='report_even' style='text-align:right'><B><font size=2><?=$this->translate->_("Total")?>:</font></B></TD>
	<TD nowrap class='report_even' style='text-align:center'></TD>
	<TD nowrap class='report_even' style='text-align:center'><input readonly style='text-align:center' type='text' name='TotalQuantity' id='TotalQuantity'  size="2" value='' title="<?=$this->translate->_("Total quantity")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><!-- RM: <input style='text-align:right' type='text' name='TotalUnitPrice' id='TotalUnitPrice'  size="6" value='' title="Total unit price."> --></TD>
	
	<TD nowrap class='report_even' style='text-align:center'><div  style='float:left;' id="LabelCurrency"><?=$this->Currency?></div>: <input style='text-align:right;' readonly size=5 type='text' name='TotalDiscount' id='TotalDiscount'  size="6" value='' title="<?=$this->translate->_("Total discounts")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><input readonly style='text-align:right' type='text' name='TotalTotalPrice' id='TotalTotalPrice'  size="6" value='' title="<?=$this->translate->_("Total price in default currency")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><input readonly style='text-align:right' type='text' name='TotalTotalItemPrice' id='TotalTotalItemPrice'  size="6" value='' title="<?=$this->translate->_("Total unit price")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><input readonly style='text-align:right' type='text' name='TotalDeliveryCost' id='TotalDeliveryCost'  size="6" value='' title="<?=$this->translate->_("Total delivery cost")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><input readonly style='text-align:right' type='text' name='TotalTaxCost' id='TotalTaxCost'  size="6" value='' title="<?=$this->translate->_("Total tax cost")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><input readonly style='text-align:right' type='text' name='TotalLandedCost' id='TotalLandedCost'  size="6" value='' title="<?=$this->translate->_("Total landed cost")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'></TD>
	<TD nowrap class='report_even' style='text-align:center'></TD>
	<TD nowrap class='report_even' style='text-align:center'></TD>
	<TD width=80px nowrap class='report_even' style='text-align:center'></TD>
  </TR>  
 
</TABLE>
<? if (!$this->Locked && $this->allowEdit) { ?> <input type=submit name='save_po' id='save_po2' value='<?=$this->translate->_('Save Details')?>'>  
<input type=button value='Cancel Changes' id='CancelChanges2' name='CancelChanges2'><? } ?>
<? if ($this->allowUpdateMarkup) { ?> 
<input type=submit name='update_markup' id='update_markup' value='<?=$this->translate->_('Save Markup Details')?>'>  
<? } ?>

	<BR>

</form>
<? } ?>

<? //$this->content_item?>
<BR><BR><BR>

