

<script language='Javascript'>
function validateEmail(email) { 
    var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
} 

$(document).ready(function() { 

$('#Name').poshytip({ bgImageFrameSize:9, className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#Location').poshytip({ bgImageFrameSize:9, className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#Address').poshytip({ bgImageFrameSize:9,className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#Phone').poshytip({ bgImageFrameSize:9,className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#Email').poshytip({ bgImageFrameSize:9,className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});

$('#search_branches').poshytip({ bgImageFrameSize:9,className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#clear').poshytip({ bgImageFrameSize:9,className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#add_branches').poshytip({ bgImageFrameSize:9,className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#save_branches').poshytip({ bgImageFrameSize:9,className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});

	$('#add_branches').click(function () {
		var error = false;
        if ($('#Name').val()=='') {   
			$('#Name').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter the name')?>.', showOn:'none', className: 'tip-yellow', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,timeOnScreen: 3000});
			$('#Name').poshytip('show');
			error = true;
		}	
		if ($('#Email').val() != ""){
			if (!validateEmail($('#Email').val())) {   
				$('#Email').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter a valid email address')?>.', showOn:'none', className: 'tip-yellow', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,timeOnScreen: 3000});
				$('#Email').poshytip('show');
				error = true;
			}
		}		
		if (error)
			return false; 			
		
	})
	
	
	$('#save_vendors').click(function () {
		var error = false;
        if ($('#Name').val()=='') {   
			$('#Name').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter the name')?>.', showOn:'none', className: 'tip-yellow', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,timeOnScreen: 3000});
			$('#Name').poshytip('show');
			error = true;
		}	
		
		if ($('#Email').val() != ""){
			if (!validateEmail($('#Email').val())) {   
				$('#Email').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter a valid email address')?>.', showOn:'none', className: 'tip-yellow', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,timeOnScreen: 3000});
				$('#Email').poshytip('show');
				error = true;
			}
		}
		if (error)
			return false; 			
		
	})
	
});	



function OnDeleteBranches(branches_id){
	$.prompt(
		"<?=$this->translate->_('Are you sure you want to remove the branch?')?>",{
		buttons: { Ok: true, Cancel: false },
		submit:function(e,v,m,f){
					if(v){
						document.location='/admin/system/branches/remove_branches/'+branches_id;
					}
				  }
	});
}





</script>

<B class='PageHeader'>Branches</B><BR>

<form action='/admin/system/branches' method=POST>
	<table border=0 cellspacing=2 cellpadding=2>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Name')?><font class='required'>*</font></TD><TD class='form_field'><input type='text' name='Name' id='Name' width=35 value='<?=$this->Name?>' title="<?=$this->translate->_("Branch full name")?>."></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Location')?></TD><TD class='form_field'><input type='text' name='Location' id='Location' width=35 value='<?=$this->Location?>' title="<?=$this->translate->_("Branch location")?>."></TD></TR>
		<TR><TD class='form_label'><?=$this->translate->_('Address')?></TD><TD class='form_field'><textarea name='Address' id='Address' cols=35 rows=5 title="<?=$this->translate->_("Vendor's address")?>."><?=$this->Address?></textarea></TD></TR>
		<TR><TD class='form_label'><?=$this->translate->_('Phone')?></TD><TD class='form_field'><input type='text' name='Phone' id='Phone' width=35 value='<?=$this->Phone?>' title="<?=$this->translate->_("Branch main phone number")?>."></TD></TR>
		<TR><TD class='form_label'><?=$this->translate->_('Email')?></TD><TD class='form_field'><input type='text' name='Email' id='Email' width=35 value='<?=$this->Email?>'  title="<?=$this->translate->_("Branch main email address")?>."></TD></TR>
		<TR><TD colspan=3 height=10px></TD></TR>

		<TR><TD colspan=3>
<?if ($this->edit_branches) { ?>
		<input type=button name='clear' id='clear' value='<?=$this->translate->_('Cancel')?>' onclick='document.location="/admin/system/branches"'  title='<?=$this->translate->_("Cancel the edit")?>.'> | 
		<input type=submit name='save_branches' id='save_branches' value='<?=$this->translate->_('Save')?>'  title='<?=$this->translate->_("Save the update for the selected branch")?>.'>
		<input type=hidden name='save_branches_id' value='<?=$this->edit_branches?>'>		
		<? } else {?>
		<input type=submit name='search_branches' id='search_branches' value='<?=$this->translate->_('Search')?>' title='<?=$this->translate->_("Click to search for the branch")?>.'>		
		<input type=button name='clear' id='clear' value='<?=$this->translate->_('Clear')?>' onclick='document.location="/admin/system/branches"'  title='<?=$this->translate->_("Clear all the inputs above")?>.'> | 
		<input type=submit name='add_branches' id='add_branches' value='<?=$this->translate->_('Create New Branch')?>'  title='<?=$this->translate->_("Please make sure all the required fields are entered before click to create new branch")?>.'>		
		<? } ?>
		
		
		
		
		</TD></TR>
	</table>
</form>
<?=$this->content_branches?>
<BR><BR><BR>
