

<script language='Javascript'>
function SaveSO()
{
	var error = false;
	
	if ($('#OrderNumber').val()=='') { 
		
		$('#OrderNumber').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please enter the Sales Order Number")?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
		$('#OrderNumber').poshytip('show');
		$('#OrderNumber').css("border", "1px solid red");
		
		error = true;
	}
	
		
	if ($('#CustomerID').val()=='' || $('#CustomerID').val()=='add-new' ) { 
		
		$('#CustomerID').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please select the customer")?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
		$('#CustomerID').poshytip('show');
		$('#CustomerID').css("border", "1px solid red");
		error = true;
	}
	if ($('#BranchID').val()=='' || $('#BranchID').val()=='add-new' ) { 
		
		$('#BranchID').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please select the branch")?>.', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
		$('#BranchID').poshytip('show');
		$('#BranchID').css("border", "1px solid red");
		
		error = true;
	}	
	$( "[id='ItemID']" ).each(function( index, element  ) {
		if (element.value == "" && !error )
		{
			$.prompt("<?=$this->translate->_("Please select the item before clicking Save")?>.",{ title: "<?=$this->translate->_("Invalid Entry")?>", buttons: { Ok: true }});
			$(element).css("border", "1px solid red");
			error = true;	
		}
	});	
		

	var totalPrice = 0;
	$( "[id='Quantity']" ).each(function( index, element  ) {
		if ((isNaN(element.value) || element.value == 0) && !error ){
			$.prompt("<?=$this->translate->_("Please enter all the valid quantity for all the items")?>.",{ title: "<?=$this->translate->_("Invalid Entry")?>", buttons: { Ok: true }});
			$(element).css("border", "1px solid red");
			
			
			error = true;		
		}
	});	
	

		
		
	if (error)
		return false; 
	else
		return true;
}

function ResetItemNumbers()
{
	$( "[id='itemcounter']" ).each(function( index, element  ) {
		element.innerHTML = (index + 1);
	});
}

function CalculateRMConvert()
{
	var Subtotal = 0;
	var Multiplier = 0;
	
	if (!isNaN(parseFloat($('#Subtotal').val()))){
		Subtotal = parseFloat($('#Subtotal').val());
	}
	if (!isNaN(parseFloat($('#Multiplier').val()))){
		Multiplier = parseFloat($('#Multiplier').val());
	}
	
//	$('#SubtotalRM').val(parseFloat(parseFloat(Subtotal) * parseFloat(Multiplier)).toFixed(2));
	$('#SubtotalLocal').val(parseFloat(parseFloat(Subtotal) / parseFloat(Multiplier)).toFixed(2));
	
	CalculateAverageAdditional();
}

function CalculateFinalCosting()
{
	var SubtotalCurrency = 0;
	var SODeliveryCharge = 0;
	var MiscCost = 0;
	var SOTaxCharge = 0;


	
	if (!isNaN(parseFloat($('#SubtotalCurrency').val()))){
		SubtotalCurrency = parseFloat($('#SubtotalCurrency').val());
		$('#SubtotalCurrency').val(parseFloat($('#SubtotalCurrency').val()).toFixed(2));
	}
	
	if (!isNaN(parseFloat($('#SODeliveryCharge').val()))){
		SODeliveryCharge = parseFloat($('#SODeliveryCharge').val());
		$('#SODeliveryCharge').val(parseFloat($('#SODeliveryCharge').val()).toFixed(2));
	}
		

	if (!isNaN(parseFloat($('#SOTaxCharge').val()))){
		SOTaxCharge = parseFloat($('#SOTaxCharge').val());
		$('#SOTaxCharge').val(parseFloat($('#SOTaxCharge').val()).toFixed(2));
	}
	
	$('#Total').val(parseFloat(SODeliveryCharge + SubtotalCurrency + SOTaxCharge).toFixed(2));
}

function CalculateDifference()
{
	CalculateAverageAdditional();
}
function getNumber(theNumber)
{
    if(theNumber > 0){
        return "+" + theNumber;
    }else{
        return theNumber.toString();
    }
}
function CalculateAverageAdditional()
{
	
	var totalSize = $( "[id='ItemID']" ).size();
	var totalQuantity = 0;
	var totalUnitPrice = 0;
	var totalUnitTotal = 0;
	var totalUnitTotalCurrency = 0;
	var totalSubtotal = 0;
	
	
	$( "[id='ItemID']" ).each(function( index, element  ) {
	
	
		var thisQuantity = parseFloat($(this).parent().parent("TR").find("[id='Quantity']").val());
		if (isNaN(thisQuantity))
			thisQuantity = 0;

		
		var thisUnitPrice = parseFloat($(this).parent().parent("TR").find("[id='UnitPrice']").val());
		if (isNaN(thisUnitPrice))
			thisUnitPrice = 0;

		var Multiplier = parseFloat($('#Multiplier').val());
		
		var thisUnitTotal = parseFloat(thisQuantity * thisUnitPrice).toFixed(2);
		if (isNaN(thisUnitTotal))
			thisUnitTotal = 0;
		$(this).parent().parent("TR").find("[id='UnitTotal']").val(parseFloat(thisUnitTotal).toFixed(2));
		
		
		var UnitTotalCurrency = 0;
		if (isNaN(Multiplier))
			UnitTotalCurrency = thisUnitTotal;
		else
			UnitTotalCurrency = parseFloat((thisQuantity * thisUnitPrice) / Multiplier).toFixed(2);
		
		if (isNaN(UnitTotalCurrency))
			UnitTotalCurrency = 0;
		$(this).parent().parent("TR").find("[id='UnitTotalCurrency']").val(parseFloat(UnitTotalCurrency).toFixed(2));
		
		var thisSubtotal = UnitTotalCurrency;

		var thisUnitDiscount = parseFloat($(this).parent().parent("TR").find("[id='UnitDiscount']").val()).toFixed(2);
		var thisUnitDiscountType = $(this).parent().parent("TR").find("[id='UnitDiscountType']").val();
		
		
		if (thisUnitDiscountType == "%" && !isNaN(thisUnitDiscount))
		{
			thisSubtotal = UnitTotalCurrency - ((UnitTotalCurrency * thisUnitDiscount) / 100);
		}else if (thisUnitDiscountType == "$" && !isNaN(thisUnitDiscount)){
			thisSubtotal = UnitTotalCurrency - thisUnitDiscount;
		}
		
		$(this).parent().parent("TR").find("[id='SubTotal']").val(parseFloat(thisSubtotal).toFixed(2));

			
			
			
		totalQuantity += thisQuantity;
		//totalUnitPrice += thisUnitPrice;
		totalUnitTotal += parseFloat(thisUnitTotal);
		totalUnitTotalCurrency += parseFloat(UnitTotalCurrency);
		totalSubtotal += parseFloat(thisSubtotal);
	});
	
	$( "#TotalQuantity" ).val(totalQuantity);
	$( "#TotalTotalPrice" ).val(parseFloat(totalUnitTotal).toFixed(2));
	$( "#TotalTotalPriceCurrency" ).val(parseFloat(totalUnitTotalCurrency).toFixed(2));
	var totalDiscount = parseFloat(parseFloat(totalSubtotal) - parseFloat(totalUnitTotalCurrency)).toFixed(2);
	$( "#TotalDiscount" ).val(totalDiscount);
	$( "#TotalTotal" ).val(parseFloat(totalSubtotal).toFixed(2));
	
	$("#Subtotal").val(parseFloat(totalUnitTotal).toFixed(2));
	$("#SODiscount").val(totalDiscount);
	$("#SubtotalCurrency").val(parseFloat(parseFloat(totalUnitTotalCurrency) + parseFloat(totalDiscount)).toFixed(2));

	CalculateFinalCosting();
	
	/// AUTO SAVE //
	if (!<?=$this->Locked?>){
		$.post('/inventory/so/index/edit_so/<?=$this->edit_so?>/save_so/1/', $('#MainSOForm').serialize(), function( data ) {
			console.log(data);
		});	 
	}
	
	

}


$(document).ready(function() { 
 $( "#SalesDate" ).datepicker({changeYear: true , yearRange: '2010:<?=Date("Y", time())+1?>', dateFormat: 'dd-mm-yy'});

$('#POFile').poshytip({ className: 'tip-yellow', showOn: 'hover', alignTo: 'target',offsetY: 10, offsetX: 1, alignX: 'inner-left', showTimeout: 100});
$('#OrderNumber').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#SalesDate').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#Multiplier').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});


$('#search_item').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#clear').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#add_item').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#save_item').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#remove_image').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});

ResetItemNumbers();
CalculateDifference();
//CalculateAverageAdditional();


$('#save_so').click(function () {
	return SaveSO();
})
$('#save_so2').click(function () {
	return SaveSO();
})
	
$('#create_so').click(function () {
	return SaveSO();			
	
})
<? if ($this->edit_so) {?>
$('#unlock_so').click(function () {
	

	var stateslock = {
		state0:  {
			title: '<?=$this->translate->_("Enter system password")?>.',
			html:'<?=$this->translate->_("Please enter your system password to un lock the Sales Order")?><BR>'+
				'<label><B><?=$this->translate->_("Password")?>:</B> <input type="Password" name="Password" value=""></label><br />',
			buttons: { Save: true, Cancel: false },
			submit:function(e,v,m,f){ 
				if (v)
				{
					 $.post("/inventory/so/ajaxunlockso",{ID:"<?=$this->userInfo->ID?>", Password:f['Password'], SOID:<?=$this->edit_so?>},function(result){
						
						
						if(!parseInt(result)){
							e.preventDefault();
							$.prompt.goToState('state1');
							return false;
						}else{
							$.prompt.close();
							document.location='/inventory/so/index/edit_so/<?=$this->edit_so?>/'
							
						}	
					 });
					
				}
				else
					$.prompt.close();
				return false;
			
			}
		},
		state1: {
			title: '<?=$this->translate->_("Enter system password")?>.',
			html:'<?=$this->translate->_("Your password is not correct")?>. ',
			buttons: { Back: -1, Exit: 0 },
			focus: 1,
			submit:function(e,v,m,f){
				e.preventDefault();
				if(v==0)
					$.prompt.close();
				else if(v==-1)
					$.prompt.goToState('state0');
			}
		},
	};

	$.prompt(stateslock);		

	return false;
})


$('#lock_so').click(function () {
	
	if (SaveSO())
	{
		var stateslock = {
			state0:  {
				title: '<?=$this->translate->_("Enter system password")?>.',
				html:'<?=$this->translate->_("Please enter your system password to lock the sales order")?><BR>'+
					'<label><B><?=$this->translate->_("Password")?>:</B> <input type="Password" name="Password" value=""></label><br />',
				buttons: { Save: true, Cancel: false },
				submit:function(e,v,m,f){ 
					if (v)
					{
						 $.post("/inventory/so/ajaxlockso",{ID:"<?=$this->userInfo->ID?>", Password:f['Password'], SOID:<?=$this->edit_so?>},function(result){
							
							
							if(!parseInt(result)){
								e.preventDefault();
								$.prompt.goToState('state1');
								return false;
							}else{
								$.prompt.close();
								document.location='/inventory/so/index/edit_so/<?=$this->edit_so?>/'
								
							}	
						 });
						
					}
					else
						$.prompt.close();
					return false;
				
				}
			},
			state1: {
				title: '<?=$this->translate->_("Enter system password")?>.',
				html:'<?=$this->translate->_("Your password is not correct")?>. ',
				buttons: { Back: -1, Exit: 0 },
				focus: 1,
				submit:function(e,v,m,f){
					e.preventDefault();
					if(v==0)
						$.prompt.close();
					else if(v==-1)
						$.prompt.goToState('state0');
				}
			},
		};

		$.prompt(stateslock);		
	}
	return false;
})
<? } ?>	

	
	

$('#Subtotal').change(function () {
	CalculateFinalCosting();
	CalculateDifference();
})

$('#SODeliveryCharge').change(function () {
	CalculateFinalCosting();
	CalculateDifference();
	CalculateAverageAdditional();
})

$('#SOTaxCharge').change(function () {
	CalculateFinalCosting();
	CalculateDifference();
	CalculateAverageAdditional();
})

// Calculating Currency Multiplier //
$('#Currency').change(function () {
	CalculateRMConvert();
	$( "[id='LabelCurrency']" ).each(function( index, element  ) {
		$(element).html($('#Currency').val()+":&nbsp;");
	});	
	
	$("#ItemCurrencyHeaderSubtotal").html("("+$('#Currency').val()+")");
	$("#ItemCurrencyHeaderTotal").html("("+$('#Currency').val()+")");	

	
	$.get("/admin/system/ajaxgetcurrency",{TargetCurrency:$('#Currency').val()},function(result){
		$('#Multiplier').val(result);
		CalculateAverageAdditional();	
	});	

	
		
})
	$("#ItemCurrencyHeaderSubtotal").html("("+$('#Currency').val()+")");
	$("#ItemCurrencyHeaderTotal").html("("+$('#Currency').val()+")");
	$( "[id='LabelCurrency']" ).each(function( index, element  ) {
		$(element).html($('#Currency').val()+":&nbsp;");
	});	
	
$('#Multiplier').change(function () {
	CalculateRMConvert();
	CalculateAverageAdditional();
})
$('#ProductCost').change(function () {
	CalculateRMConvert();
	CalculateAverageAdditional();
})
// Calculating Currency Multiplier //
	
	
	
	

var i = $('#report_table TR').size() + 1;

$('#AddItems').click(function () {
		
	$.ajaxSetup({ cache: false });
	$.get( "/inventory/so/ajaxadditem/orderid/<?=$this->edit_so?>", function( data ) {
		$('#report_table_footer').before(data); 

		ResetItemNumbers();
		CalculateAverageAdditional();

		
	});
	//$('#report_table').append("<TR class='report_even'><TD class='report_cell'  style='text-align:center'>1</TD><TD class='report_cell'  style='text-align:center'>7</TD><TD class='report_cell'  style='text-align:center'><img src='/uploads/ItemImage/small/7.jpg'></TD><TD class='report_cell'  style='text-align:left'>Applied Analytics</TD><TD class='report_cell'  style='text-align:left'>TLG 837 Tail Gas Analyzer</TD><TD class='report_cell'  style='text-align:left'>TLG 837</TD><TD class='report_cell'  style='text-align:left'>&nbsp</TD><TD class='report_cell'  style='text-align:right'>RM 12.45</TD><TD class='report_cell'  style='text-align:center'><img border=0 src='/images/icons/IconDelete.gif' id='RemoveRow' name='RemoveRow'></TD></TR>");
	
})
	
	<? if ($this->edit_po)  { ?>
	$('#CancelChanges').click(function () {
		document.location = "/inventory/po/index/edit_po/"+<?=$this->edit_po?>;
	})	
	$('#CancelChanges2').click(function () {
		document.location = "/inventory/po/index/edit_po/"+<?=$this->edit_po?>;
	})		
	
	<? } ?>
	
	
	$(document).on("change", "#UnitPrice", function(){	
		CalculateDifference();
	})
		
	$(document).on("change", "#Quantity", function(){	
		CalculateDifference();
	})
	
	$(document).on("change", "#UnitDiscount", function(){	
		CalculateDifference();
	})
	
	$(document).on("change", "#UnitDiscountType", function(){	
		if ($(this).val() == "")
		{
			$(this).parent().parent("TR").find("[id='UnitDiscount']").val("");	
		}
		CalculateDifference();
	})
	
//	$(document).on("change", "#ItemID", function(){	
//		var counter = 0; var selectedID = $(this).val();
//		$( "[id='ItemID']" ).each(function( index, element  ) {
//			if (selectedID == element.value){
//				counter += 1;
//			}
//		});	
//		
//		if (counter > 1){
//			$.prompt("The selected item already exist in the list.",{ title: "Invalid Entry", buttons: { Ok: true }});
//			$(this).val("");
//			$(this).css("border", "1px solid red");
//		}
//		return false;
//	})
	
	
	
	
	$(document).on("click", "#RemoveRowConfirm", function(){	
	
		var thisSOItemsID = $(this).parent().parent("TR").find("[id='SOItemsID']").val();
		var thisObj = $(this).parents("TR");
		$.prompt(
		"<?=$this->translate->_('Are you sure you want to remove this item?')?>",{
		buttons: { Ok: true, Cancel: false },
		submit:function(e,v,m,f){ 
			if(v){
				$.ajaxSetup({ cache: false });
				$.get( "/inventory/so/ajaxremovesoitems/soitemsid/"+thisSOItemsID, function( data ) {
					document.location='/inventory/so/index/edit_so/<?=$this->edit_so?>?r=<?=time()?>#selectItem';
	//				thisObj.remove();
	//				
	//				$( "[id='itemcounter']" ).each(function( index, element  ) {
	//					element.innerHTML = (index + 1);
	//				});
	//		
	//				CalculateDifference();
	//				CalculateAverageAdditional();							
					
				});						
			}
		}
	  
		});
	});
	
	
	$(document).on("click", "#RemoveRow", function(){	
	
		var thisSOItemsID = $(this).parent().parent("TR").find("[id='SOItemsID']").val();
		var thisObj = $(this).parents("TR");

		$.ajaxSetup({ cache: false });
		$.get( "/inventory/so/ajaxremovesoitems/soitemsid/"+thisSOItemsID, function( data ) {

			thisObj.remove();
			
			$( "[id='itemcounter']" ).each(function( index, element  ) {
				element.innerHTML = (index + 1);
			});
			
			
			CalculateDifference();
			CalculateAverageAdditional();							
			
		});						

	});
	$(document).on("focus", "#Quantity", function(){	
		var thisItemID = $(this).parent().parent("TR").find("[id='ItemID']").val();
		if (thisItemID == "")
		{
			$.prompt("<?=$this->translate->_("Please select the item first")?>.",{ title: "<?=$this->translate->_("Invalid Entry")?>", buttons: { Ok: true }});				
		}
		objItemID = $(this).parent().parent("TR").find("[id='ItemID']");
		objItemID.select();
	})	
	

	
	var selectSeriesFunction = function () {
		var thisSOItemsID = $(this).parent().parent("TR").find("[id='SOItemsID']").val();
		var thisQuantityObj = $(this).parent().parent("TR").find("[id='Quantity']");
		var thisQuantity = $(this).parent().parent("TR").find("[id='Quantity']").val();
		var thisItemsTotalSelected = $(this).parent().parent("TR").find("[id='ItemsTotalSelected']").val();
		var thisItemID = $(this).parent().parent("TR").find("[id='ItemID']").val();
		var objItem = $(this).parent().parent("TR").find("[id='ItemID']");

		var thisUnitPriceObj = $(this).parent().parent("TR").find("[id='UnitPrice']");
		
		
		var thisItemText = objItem.find("option:selected").text();
		var matches = thisItemText.match(/\(([0-9]+)\)/);		
		if (parseInt(matches[1]) + parseInt(thisItemsTotalSelected) == 0)
		{
			$.prompt("<?=$this->translate->_("The selected item no longer in stock")?>.",{ title: "<?=$this->translate->_("Invalid Entry")?>", buttons: { Ok: true }});				
			return ;
		}
		
		
//		if ((thisQuantity > 0))
//		{

//			  if (parseInt(thisQuantity) > (parseInt(matches[1]) + parseInt(thisItemsTotalSelected)))
//			  {
//					$.prompt("<?=$this->translate->_("The quantity exceeded the number of stock in store. Please enter a valid quantity")?>.",{ title: "<?=$this->translate->_("Invalid Entry")?>", buttons: { Ok: true }});				
//					//thisQuantityObj.val("");
//					thisQuantityObj.focus();
//					return;
//			  }
			  
			  var objItems = $(this);
			  $.ajaxSetup({
					// Disable caching of AJAX responses
					cache: false
				});

				$( "#dialog-qty" ).dialog({
				   autoOpen: false,
				   modal: true,
				   width: '900',
				   height: '650',
					buttons: {
					  'Close': function() {
						$( "#dialog-qty" ).html("");
						$(this).dialog('close');
						thisUnitPriceObj.val("0");
						document.location='/inventory/so/index/edit_so/<?=$this->edit_so?>?r=<?=time()?>#selectItem';
						//window.location.reload(true);
					  }
					 }
				  
				});						
				

				$( "#dialog-qty" ).dialog("open");
				$( "#dialog-qty" ).html("<img src='/images/icons/IconIndicator.gif'>");
				$.get( "/inventory/brand/getitemserieslist/", {itemID:thisItemID, quantity:thisQuantity, SOItemID:thisSOItemsID}, function( data ) {
					 $( "#dialog-qty" ).html(data);
					   
					  
				}, "html");
//			var thisQuantity = $(this).parent().parent("TR").find("[id='Quantity']").val();
//			$.get( "/inventory/so/ajaxsavesoitemq/SOItemsID/"+thisSOItemsID+"/Quantity/"+thisQuantity, function( data ) {
//				console.log(data);
//			});
			
				
//		}else
//		{
//			$.prompt("<?=$this->translate->_("Please enter quantity before proceed")?>.",{ title: "<?=$this->translate->_("Invalid Entry")?>", buttons: { Ok: true }});				
//					
//		}
	}	
		
	$(document).on("click", "#SelectSeries", selectSeriesFunction);	
	$(document).on("change", "#Quantity", selectSeriesFunction);		

		
	$( "#dialog-message" ).dialog({
	   autoOpen: false,
	   modal: true,
	   width: '600',
	   height: '450',
        buttons: {
          'Close': function() {
            $(this).dialog('close');
				$.get( "/admin/system/getbranches/", function( data ) {
					  $( "#BranchID" ).html(data);
				}, "html");			
          }
		 }
	  
	});	

	$('#BranchID').change(function () {
		if (($(this).val() == "add-new"))
		{
			  $.ajaxSetup({
					// Disable caching of AJAX responses
					cache: false
				});

				$( "#dialog-message" ).dialog("open");
				$( "#dialog-message" ).html("<img src='/images/icons/IconIndicator.gif'>");
				$.get( "/admin/system/addbranches/", function( data ) {
					 $( "#dialog-message" ).html(data);
					   
					  
				}, "html");
		}
	
	})		
	
					
	$( "#dialog-message-customer" ).dialog({
	   autoOpen: false,
	   modal: true,
	   width: '600',
	   height: '450',
        buttons: {
          'Close': function() {
            $(this).dialog('close');
				$.get( "/admin/system/getcustomers/", function( data ) {
					  $( "#CustomerID" ).html(data);
				}, "html");			
          }
		 }
	  
	});	

	$('#CustomerID').change(function () {
		if (($(this).val() == "add-new"))
		{
			  $.ajaxSetup({
					// Disable caching of AJAX responses
					cache: false
				});

				$( "#dialog-message-customer" ).dialog("open");
				$( "#dialog-message-customer" ).html("<img src='/images/icons/IconIndicator.gif'>");
				$.get( "/admin/system/addcustomers/", function( data ) {
					 $( "#dialog-message-customer" ).html(data);
					   
					  
				}, "html");
		}
	
	})

	
	function selectItems(obj, refresh) 
	{

		if ((obj.val() == "add-new"))
		{
		
			  //var objItems = $(this);
			  $.ajaxSetup({
					// Disable caching of AJAX responses
					cache: false
				});

				$( "#dialog-message-items" ).dialog({
				   autoOpen: false,
				   modal: true,
				   width: '600',
				   height: '450',
					buttons: {
					  'Close': function() {
						$(this).dialog('close');
							$.get( "/inventory/brand/getitem/", function( data ) {
								  obj.html(data);
							}, "html");								
					  }
					 }
				  
				});						
				

				$( "#dialog-message-items" ).dialog("open");
				$( "#dialog-message-items" ).html("<img src='/images/icons/IconIndicator.gif'>");
				$.get( "/inventory/brand/additem/", function( data ) {
					 $( "#dialog-message-items" ).html(data);
					   
					  
				}, "html");
		}
		var thisSOItemsID = obj.parent().parent("TR").find("[id='SOItemsID']").val();
		var thisOriginalItemID = obj.parent().parent("TR").find("[id='OriginalItemID']").val();
		$.get( "/inventory/so/ajaxsavesoitem/ItemID/"+obj.val()+"/SOItemsID/"+thisSOItemsID+"/OriginalItemID/"+thisOriginalItemID, function( data ) {
			if (refresh){
				document.location='/inventory/so/index/edit_so/<?=$this->edit_so?>';
			}
		});
	}	
	

	$(document).on("change", "#ItemID", function(){	
		var obj = $(this);
		var thisItemsTotalSelected = obj.parent().parent("TR").find("[id='ItemsTotalSelected']").val();
		if (thisItemsTotalSelected > 0)
		{
				
			var stateslock = {
				state0:  {
					title: '<?=$this->translate->_("Previous items selection detected")?>.',
					html:'<?=$this->translate->_("There were items selected for the previous selection. Do you want to proceed and remove previously selected items?")?>',
					buttons: { Continue: true, Cancel: false },
					submit:function(e,v,m,f){ 
						if (v){
							selectItems(obj, true);
						}else{
							$.prompt.close();
							return false;
						}
					}
				}
			};

			$.prompt(stateslock);
		}else
			selectItems(obj, false);
		
		
		
	})	
	
	
	
});	





</script>
<div id="dialog-qty" title="<?=$this->translate->_('Item Quantity')?>"></div>
<div id="dialog-message" title="<?=$this->translate->_('Add New Branch')?>"></div>
<div id="dialog-message-customer" title="<?=$this->translate->_('Add New Customer')?>"></div>
<div id="dialog-message-items" title="<?=$this->translate->_('Add New Items')?>"></div>

<B class='PageHeader'><?=$this->translate->_('Sales Orders')?></B><BR>

<form  enctype="multipart/form-data"  action='/inventory/so' method=POST id='MainSOForm'>
	<table border=0 cellspacing=2 cellpadding=2>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Upload Document')?></TD><TD  class='form_field' valign=bottom><?if ($this->SOFilePath) echo "<a target='_new' href='".$this->SOFilePath."'><img border=0 src='/images/icons/IconView.png'></a>&nbsp;&nbsp;&nbsp;<input type=submit name='remove_file' id='remove_file' value='".$this->translate->_('Remove File')."' title='".$this->translate->_('Click to remove the PO document. Select a differnt file to replacement existing one').".'>"?><BR><input type='file' name='SOFile' id='SOFile' size="35" title="<?=$this->translate->_('The file must be less than or equal to 1MB in size')?>."></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Order Number')?><font class='required'>*</font></TD><TD class='form_field'><input <?=$this->disabled?> type='text' name='OrderNumber' id='OrderNumber' size="35" value='<?=$this->OrderNumber?>' title="<?=$this->translate->_('Sales order number')?>."></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Branch')?><font class='required'>*</font></TD><TD class='form_field' valign=bottom> <select <?=$this->disabled?> name='BranchID' id='BranchID' title=""><option value=''>-</option><?=$this->optionBranches?><option value='add-new'><<< <?=$this->translate->_('ADD NEW')?> >>></option></select></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Customer')?><font class='required'>*</font></TD><TD class='form_field' valign=bottom> <select <?=$this->disabled?> name='CustomerID' id='CustomerID' title=""><option value=''>-</option><?=$this->optionCustomers?><option value='add-new'><<< <?=$this->translate->_('ADD NEW')?> >>></option></select></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Sales Date')?></TD><TD class='form_field'><input type='text' <?=$this->disabled?> name='SalesDate' id='SalesDate' size="10" value='<?=$this->SalesDate?>' title="<?=$this->translate->_("Sales order date")?>."></TD></TR>
		<?if ($this->edit_so) { ?>
		<TR><TD class='form_label' height=80px width=150px><?=$this->translate->_('Subtotal')?></TD><TD class='form_field'>
		<SELECT <?=$this->disabled?> Name="Currency" ID="Currency"><?=$this->optionCurrency?></select>: <input readonly style='text-align:right' type='text' <?=$this->disabled?> name='Subtotal' id='Subtotal'  size="10" value='<?=$this->Subtotal?>' title="<?=$this->translate->_("Sales order's total product / item cost. Not include transport or misc charges")?>.">
		/ <input <?=$this->disabled?> size=5 type="text" name="Multiplier" id="Multiplier" value="<?=$this->Multiplier?>" title="<?=$this->translate->_('Updated exchange rate base on Yahoo Finance currency quote.')?>"> 
		= <HR style='margin: 5px;'><div style='float:left;' id='LabelCurrency'><?=$this->currency?>: </div><input readonly size=10 style='text-align:right' type="text" name="SubtotalCurrency" id="SubtotalCurrency" value="<?=$this->SubtotalCurrency?>"> 
		</TD></TR>
		
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Delivery Cost')?></TD><TD class='form_field'><div style='float:left;' id='LabelCurrency'><?=$this->currency?>: </div><input <?=$this->disabled?> style='text-align:right' type='text' name='SODeliveryCharge' id='SODeliveryCharge'  size="10" value='<?=$this->SODeliveryCharge?>' title="<?=$this->translate->_("Sales order's misc charges")?>.">		</TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Total Tax')?></TD><TD class='form_field'><div style='float:left;' id='LabelCurrency'><?=$this->currency?>: </div><input <?=$this->disabled?> style='text-align:right' type='text' name='SOTaxCharge' id='SOTaxCharge'  size="10" value='<?=$this->SOTaxCharge?>' title="<?=$this->translate->_("Total tax applied to all the items")?>.">
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Total Discount')?></TD><TD class='form_field'><div style='float:left;' id='LabelCurrency'><?=$this->currency?>: </div><input readonly <?=$this->disabled?> style='text-align:right' type='text' name='SODiscount' id='SODiscount'  size="10" value='<?=$this->SODiscount?>' title="<?=$this->translate->_("Total discounts given")?>.">
		<!--RM: <input readonly style='text-align:right' type='text' name='TotalTaxCost' id='TotalTaxCost'  size="8" value='' title="Total tax cost.">
		<input readonly style='text-align:right' type='text' name='TotalTaxCostDiff' id='TotalTaxCostDiff'  size="8" value='' title="Total tax cost.">
		-->
		</TD></TR>
		
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Total')?></TD><TD class='form_field'><div style='float:left;' id='LabelCurrency'><?=$this->currency?>: </div><input <?=$this->disabled?> style='text-align:right' type='text' name='Total' id='Total'  size="10" value='<?=$this->Total?>' title="<?=$this->translate->_("Sales order's final / total cost")?>.">		
		</TD></TR>
		<? } ?>
		<TR><TD colspan=2 height=10px>
		</TD></TR>
		<TR><TD colspan=2>
		<? if ($this->edit_so && !$this->Locked) { ?>
			<? if ($this->allowEdit) { ?>
			<input type=hidden name='save_so_id' id='save_so_id' value='<?=$this->edit_so?>'>
			<input type=submit name='save_so' id='save_so' value='<?=$this->translate->_('Save Details')?>'>	
			<input type=submit name='lock_so' id='lock_so' value='<?=$this->translate->_('Lock and Finalized')?>'>	
			
			<? } ?>
			<input type=button value='<?=$this->translate->_('Back to Sales Order Listing')?>' id='Back' name='Back' onclick='document.location="/inventory/so/listing"'>
<BR>
		<? } else if ($this->edit_so && $this->Locked) { ?>
			<?=$this->translate->_("This Sales Order has been locked by")?> <B><?=$this->LockedBy?></B> on <B><?=$this->LockedDate?></B><BR>
			<? if ($this->userInfo->ACLRole == "AdminSystem") {?>
			<input type=submit value='Unlock SO' id='unlock_so' name='unlock_so' value='<?=$this->translate->_('Un-Lock')?>'>
			<? } ?>
			<input type=button value='<?=$this->translate->_('Back to Sales Order Listing')?>' id='Back' name='Back' onclick='document.location="/inventory/po/listing"'>

		<? } else { ?>
			<? if ($this->allowEdit) { ?>
			<input type=submit name='create_so' id='create_so' value='<?=$this->translate->_('Proceed with Sales Order Items')?>'  title='<?=$this->translate->_("You can add items after you had created the PO")?>.'>	<BR>
			<div class='small'><?=$this->translate->_("Please fill in the basic details before proceeding with sales items.")?>.</div>
			<? } ?>
		<? } ?>
		
		
		
		
		</TD></TR>
	</table>

<BR><BR>
<? if ($this->edit_so) { ?>
<? if (!$this->Locked && $this->allowEdit) { ?> <input type=button value='Add Items' id='AddItems' name='AddItems'> <? } ?>
<a name='selectItem'></a>
<TABLE BORDER=0 align= class='report_table' id='report_table' cellspacing=0 cellpadding=3>
  <TR>
    <TD width=25px nowrap class='report_header' style='text-align:center'>#</TD>
	<TD width=350px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Items")?></TD>
	<TD width=75px nowrap class='report_header' style='text-align:center'><?=$this->translate->_("QTY")?></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Unit Sales Price")?><BR><div id="ItemCurrencyHeaderLocal" style="text-align:center; margin:0 auto;">(<?=$this->currencyType?>)</div></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Total Sales Price")?><BR><div id="ItemCurrencyHeaderTotalLocal" style="text-align:center; margin:0 auto;">(<?=$this->currencyType?>)</div></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Total Sales Price")?><BR><div id="ItemCurrencyHeaderTotal" style="text-align:center; margin:0 auto;">(<?=$this->Currency?>)</div></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Discount")?><BR></TD>
	<TD width=125px  nowrap class='report_header' style='text-align:center'><?=$this->translate->_("Sub-Total")?><BR><div id="ItemCurrencyHeaderSubtotal" style="text-align:center; margin:0 auto;">(<?=$this->Currency?>)</div></TD>
	<TD width=40px nowrap class='report_header' style='text-align:center'></TD>
  </TR>
  <?=$this->listItems ?>
  <TR id="report_table_footer"><TD class='report_even' colspan=113 style='height:2px;'></TD></TR>
  <TR>
    <TD colspan=2 nowrap class='report_even' style='text-align:right'><B><font size=2><?=$this->translate->_("Total")?>:</font></B></TD>
	<TD nowrap class='report_even' style='text-align:center'><input style='text-align:center' type='text' name='TotalQuantity' id='TotalQuantity'  size="2" value='' title="<?=$this->translate->_("Total quantity")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><!-- RM: <input style='text-align:right' type='text' name='TotalUnitPrice' id='TotalUnitPrice'  size="6" value='' title="Total unit price."> --></TD>
	<TD nowrap class='report_even' style='text-align:center'><input style='text-align:right' type='text' name='TotalTotalPrice' id='TotalTotalPrice'  size="6" value='' title="<?=$this->translate->_("Total price in default currency")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><input style='text-align:right' type='text' name='TotalTotalPriceCurrency' id='TotalTotalPriceCurrency'  size="6" value='' title="<?=$this->translate->_("Total price")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><div  style='float:left;' id="LabelCurrency"><?=$this->Currency?></div><input size=5 style='text-align:right' type='text' name='TotalDiscount' id='TotalDiscount'  size="6" value='' title="<?=$this->translate->_("Total discounts")?>."></TD>
	<TD nowrap class='report_even' style='text-align:center'><input style='text-align:right' type='text' name='TotalTotal' id='TotalTotal'  size="6" value='' title="<?=$this->translate->_("Total sales order amount")?>."></TD>
	<TD width=80px nowrap class='report_even' style='text-align:center'></TD>
  </TR>  
 
</TABLE>
<? if (!$this->Locked && $this->allowEdit) { ?> <input type=submit name='save_so' id='save_so2' value='<?=$this->translate->_('Save Details')?>'>  
<? } ?>

	<BR>

</form>
<? } ?>
<?=$this->translate->_("Note: All the items selected will have the status set to 'reserved'. The items will only be marked as 'sold' once the Sales Order
has been <B>Lock and Finalized")?></B>
<? //$this->content_item?>
<BR><BR><BR>
