

<script language='Javascript'>
</script>



	<table border=0 cellspacing=2 cellpadding=2 width=400px>
		<TR><TD colspan=2 ><B><?=$this->translate->_("Purchase Order")?></B></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('PO Document')?></TD><TD  style='text-align: right;' colspan=2 width=150px  class='form_field' valign=bottom><?if ($this->POFilePath) echo "<a target='_new' href='".$this->POPath."'><img border=0 src='".$this->POFilePath."' style='height:80px'></a>"?></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Order Number')?></TD><TD  style='text-align: right;' colspan=2 class='form_field'><B><?=$this->OrderNumber?></B></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Branch')?></TD><TD colspan=2 style='text-align: right;' class='form_field' valign=bottom> <?=$this->BranchName?></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Vendor')?></TD><TD colspan=2 style='text-align: right;' class='form_field' valign=bottom> <?=$this->VendorName?></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('PurchaseDate')?></TD><TD colspan=2 style='text-align: right;' class='form_field'><?=$this->PurchaseDate?></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Product Cost')?></TD><TD width=150px class='form_field' style='text-align: right;'>
		<?=$this->ProductCostRM?>
		</TD></TR>
		
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Delivery Cost')?></TD><TD width=150px class='form_field' style='text-align: right;'><?=$this->PODeliveryCost?>
		</TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Total Tax')?></TD><TD width=150px class='form_field' style='text-align: right;'><?=$this->POTaxCost?>
		</TD></TR>
		
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Total Costing')?></TD><TD width=150px class='form_field' style='text-align: right;'><?=$this->TotalCost?>
		</TD></TR>
	</table>

<BR><BR>

<?=$this->content_item?>
<BR><BR><BR>
