

<script language='Javascript'>


$(document).ready(function() { 


$('#BrandLogo').poshytip({ className: 'tip-yellow', showOn: 'hover', alignTo: 'target',offsetY: 10, offsetX: 1, alignX: 'inner-left', showTimeout: 100});
$('#FullName').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#ShortName').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});
$('#CompanyName').poshytip({ className: 'tip-yellow', showOn: 'focus', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5,showTimeout: 100});

$('#search_brand').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#clear').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#add_brand').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#save_brand').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});
$('#remove_logo').poshytip({ className: 'tip-yellow', alignTo: 'target', showOn: 'hover', offsetY: 10, offsetX: 1, alignX: 'inner-left',  showTimeout: 100, allowTipHover:false});



	$('#add_brand').click(function () {

		
		var error = false;
        if ($('#FullName').val()=='') { 
			
			$('#FullName').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please enter the brand name")?>', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
			$('#FullName').poshytip('show');

			error = true;
		}

        if ($('#ShortName').val()=='') { 
			
			$('#ShortName').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please enter the brand short name")?>', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
			$('#ShortName').poshytip('show');

			error = true;
		}        
		
		if ($('#CompanyName').val()=='') { 
			
			$('#CompanyName').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_("Please enter the brand\'s company name")?>', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
			$('#CompanyName').poshytip('show');

			error = true;
		}		
		
				
		if (error)
			return false; 			
		
	})
});	



function OnDeleteBrand(brand_id){
	$.prompt(
		"<?=$this->translate->_('Are you sure you want to remove this brand?')?>",{
		buttons: { Ok: true, Cancel: false },
		submit:function(e,v,m,f){ 
			if(v){
				document.location='/inventory/brand/index/remove_brand/'+brand_id;
			}
		}
	  
	});
}





</script>

<B class='PageHeader'><?=$this->translate->_("Inventory > Manage > Brand")?></B><BR>

<form enctype="multipart/form-data"  action='/inventory/brand' method=POST>
	<table border=0 cellspacing=2 cellpadding=2 class='form_table'>
		<TR><TD colspan=2 ><B><?=$this->translate->_("Brand's Details")?></B></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Brand Logo')?></TD><TD class='form_field' valign=bottom><?if ($this->BrandLogoPath) echo "<img src='".$this->BrandLogoPath."' style='height:80px'><input type=submit name='remove_logo' id='remove_logo' value='".$this->translate->_("Remove Logo")."' title='".$this->translate->_('Click to remove the logo. Select a differnt image file to replacement existing logo').".'><BR>"?><input type='file' name='BrandLogo' id='BrandLogo' size="35" title="<?=$this->translate->_("It must be in JPEG format and must be less than or equal to 1MB")?>."></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Full Name')?><font  class='required'>*</font></TD><TD class='form_field'><input type='text' name='FullName' id='FullName' size="35" value='<?=$this->FullName?>' title="<?=$this->translate->_("Complete brand's name")?>."></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Short Name')?><font  class='required'>*</font></TD><TD class='form_field'><input type='text' name='ShortName' id='ShortName'  size="10" maxlength="10" value='<?=$this->ShortName?>' title="<?=$this->translate->_("Abbreviated brand's name")?>."></TD></TR>
		<TR><TD class='form_label' width=150px><?=$this->translate->_('Company Name')?><font class='required'>*</font></TD><TD class='form_field'><input type='text' name='CompanyName' id='CompanyName'  size="35" value='<?=$this->CompanyName?>' title="<?=$this->translate->_('Company name for the brand')?>."></TD></TR>

		<TR><TD class='form_blank' colspan=2 height=10px></TD></TR>
		<TR><TD colspan=2>
<?if ($this->edit_brand) { ?>
		<input type=button name='clear' id='clear' value='<?=$this->translate->_('Cancel')?>' onclick='document.location="/inventory/brand"'  title='<?=$this->translate->_('Cancel the edit')?>.'> | 
		<input type=submit name='save_brand' id='save_brand' value='<?=$this->translate->_('Save')?>'  title='<?=$this->translate->_('Save the update for the selected brand')?>.'>
		<input type=hidden name='save_brand_id' value='<?=$this->edit_brand?>'>		
		<? } else {?>
		<input type=submit name='search_brand' id='search_brand' value='<?=$this->translate->_('Search')?>' title='<?=$this->translate->_('Click to search for the brand')?>.'>		
		<input type=button name='clear' id='clear' value='<?=$this->translate->_('Clear')?>' onclick='document.location="/inventory/brand"'  title='<?=$this->translate->_('Clear all the inputs above')?>.'> | 
		<input type=submit name='add_brand' id='add_brand' value='<?=$this->translate->_('Create New Brand')?>'  title='<?=$this->translate->_('Please make sure all the required fields are entered before click to create new brand')?>.'>		
		<? } ?>
		
		
		
		
		</TD></TR>
	</table>
</form>
<?=$this->content_brand?>
<BR><BR><BR>
