<H3>JQuery Example</H3>

 <link rel="stylesheet" type="text/css" href="/js/styles/ui.tabs.css" /> 
<script type="text/javascript" src="/js/jquery/ui/ui.base.js"></script>  
<script type="text/javascript" src="/js/jquery/ui/ui.tabs.js"></script>  




<table border="0" cellpadding="0" cellspacing="0" width="600">   
    <tr>  
        <td><div id="tab-container">   
            <ul>  
                <li> <a href="#tab1"><span>Tab 1</span></a> </li>  
                <li> <a href="#tab2"><span>Tab 2</span></a> </li>  
            </ul>  
        </div></td>   
    </tr>  
    <tr>  
        <td>  
            <div id='tab1'>   
                <table align="center" width="600" valign="top" border="0" cellpadding="0" cellspacing="0">   
                    <tr>  
                        <td width="100%" height="250" valign="top" bgcolor="#CCCCCC"> Tab 1 Content </td>  
                    </tr>  
                </table>  
            </div>  
            <div id="tab2">   
                <table align="center" width="600" valign="top" border="0" cellpadding="0" cellspacing="0">   
                    <tr>  
                        <td width="100%" height="250" valign="top" bgcolor="#0099FF">Tab 2 Content</td>  
                    </tr>  
                </table>  
            </div>  
            <br />  
        </td>  
    </tr>  
</table>  


  
<script language="JavaScript" type="text/JavaScript">   
    $(function() {   
            $('#tab-container > ul').tabs({ fx: { opacity: 'toggle' } });   
        });    
</script>   

